# Generated by Django 5.0.14 on 2026-02-10 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='verified', help_text='Material icon name', max_length=100)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower first)')),
            ],
            options={
                'verbose_name': 'Benefit',
                'verbose_name_plural': 'Benefits',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(help_text='E.g., E-commerce, SaaS', max_length=100)),
                ('description', models.TextField()),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='case_studies/')),
                ('is_featured', models.BooleanField(default=False, help_text='Show as featured on home page')),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Case Study',
                'verbose_name_plural': 'Case Studies',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CompanyStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Stat label', max_length=100)),
                ('value', models.CharField(help_text='Stat value (e.g., 500+)', max_length=50)),
                ('icon', models.CharField(default='check_circle', help_text='Material icon name', max_length=100)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower first)')),
            ],
            options={
                'verbose_name': 'Company Statistic',
                'verbose_name_plural': 'Company Statistics',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CTASection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('button_primary_text', models.CharField(max_length=100)),
                ('button_primary_url', models.CharField(max_length=200)),
                ('button_secondary_text', models.CharField(blank=True, max_length=100)),
                ('button_secondary_url', models.CharField(blank=True, max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'CTA Section',
                'verbose_name_plural': 'CTA Section',
            },
        ),
        migrations.CreateModel(
            name='Guarantee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('icon', models.CharField(default='shield', help_text='Material icon name', max_length=100)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower first)')),
            ],
            options={
                'verbose_name': 'Guarantee',
                'verbose_name_plural': 'Guarantees',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HeroBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Benefit title (e.g., AVG ROI)', max_length=100)),
                ('value', models.CharField(help_text='Benefit value (e.g., 200%)', max_length=50)),
                ('icon', models.CharField(default='trending_up', help_text='Material icon name', max_length=100)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower first)')),
            ],
            options={
                'verbose_name': 'Hero Benefit',
                'verbose_name_plural': 'Hero Benefits',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(help_text='Main headline text', max_length=200)),
                ('subheadline', models.TextField(help_text='Subheadline description')),
                ('cta_primary_text', models.CharField(default='Get Free Strategy Call', max_length=100)),
                ('cta_primary_url', models.CharField(default='#contact', max_length=200)),
                ('cta_secondary_text', models.CharField(default='Success Stories', max_length=100)),
                ('cta_secondary_url', models.CharField(default='/case-studies', max_length=200)),
                ('hero_image', models.ImageField(blank=True, help_text='Hero section image (right side visual)', null=True, upload_to='hero/')),
                ('rating_score', models.DecimalField(decimal_places=1, default=4.9, help_text='Client rating score (e.g., 4.9)', max_digits=2)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hero Section',
                'verbose_name_plural': 'Hero Section',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(help_text='Partner logo image', upload_to='partners/')),
                ('website_url', models.URLField(blank=True, help_text='Partner website (optional)')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower first)')),
            ],
            options={
                'verbose_name': 'Partner',
                'verbose_name_plural': 'Partners',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(help_text='Service description with key benefits')),
                ('icon', models.CharField(default='settings', help_text='Material icon name', max_length=100)),
                ('detail_page_url', models.CharField(help_text='URL slug (e.g., /ai-solutions)', max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='Show on home page')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower first)')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('client_title', models.CharField(help_text='E.g., CEO', max_length=100)),
                ('client_company', models.CharField(max_length=200)),
                ('client_photo', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('quote', models.TextField(help_text='Client testimonial quote')),
                ('rating', models.IntegerField(default=5, help_text='Star rating (1-5)')),
                ('is_active', models.BooleanField(default=True, help_text='Show on home page')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CaseStudyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='E.g., Organic Traffic', max_length=100)),
                ('value', models.CharField(help_text='E.g., 340%', max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('case_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='website.casestudy')),
            ],
            options={
                'verbose_name': 'Case Study Metric',
                'verbose_name_plural': 'Case Study Metrics',
                'ordering': ['order'],
            },
        ),
    ]
