# Generated by Django 5.0.14 on 2026-02-10 16:17

from django.db import migrations


def populate_home_content(apps, schema_editor):
    """Populate home page with existing hardcoded content"""
    HeroSection = apps.get_model('website', 'HeroSection')
    HeroBenefit = apps.get_model('website', 'HeroBenefit')
    CompanyStat = apps.get_model('website', 'CompanyStat')
    Service = apps.get_model('website', 'Service')
    Benefit = apps.get_model('website', 'Benefit')
    Guarantee = apps.get_model('website', 'Guarantee')
    CaseStudy = apps.get_model('website', 'CaseStudy')
    CaseStudyMetric = apps.get_model('website', 'CaseStudyMetric')
    Testimonial = apps.get_model('website', 'Testimonial')
    CTASection = apps.get_model('website', 'CTASection')
    
    # Hero Section
    hero = HeroSection.objects.create(
        headline="Drive Digital Dominance with IT Solutions",
        subheadline="Transform your business with enterprise-grade IT solutions. AI automation, custom development, and data-driven marketing that delivers measurable ROI.",
        cta_primary_text="Get Free Strategy Call",
        cta_primary_url="/contact",
        cta_secondary_text="Success Stories",
        cta_secondary_url="/case-studies",
        rating_score=4.9
    )
    
    # Hero Benefits
    HeroBenefit.objects.bulk_create([
        HeroBenefit(title="AVG ROI", value="200%", icon="check_circle", order=1),
        HeroBenefit(title="Support", value="24/7", icon="schedule", order=2),
        HeroBenefit(title="Projects", value="500+", icon="workspace_premium", order=3),
        HeroBenefit(title="Retention", value="98%", icon="verified", order=4),
    ])
    
    # Company Stats
    CompanyStat.objects.bulk_create([
        CompanyStat(label="Projects Delivered", value="500+", icon="workspace_premium", order=1),
        CompanyStat(label="Years Experience", value="10+", icon="verified", order=2),
        CompanyStat(label="Client Retention", value="98%", icon="favorite", order=3),
        CompanyStat(label="Dedicated Support", value="24/7", icon="support_agent", order=4),
    ])
    
    # Services
    Service.objects.bulk_create([
        Service(
            title="AI Solutions",
            description="Intelligent automation and machine learning solutions that reduce costs by 85%",
            icon="psychology",
            detail_page_url="/ai-solutions",
            is_active=True,
            order=1
        ),
        Service(
            title="Web Development",
            description="High-performance websites with 95+ Lighthouse scores and blazing-fast load times",
            icon="code",
            detail_page_url="/web-development",
            is_active=True,
            order=2
        ),
        Service(
            title="Digital Marketing",
            description="SEO-first strategies driving 248% revenue growth and 10x qualified leads",
            icon="trending_up",
            detail_page_url="/digital-marketing",
            is_active=True,
            order=3
        ),
        Service(
            title="App Development",
            description="Native iOS/Android and cross-platform apps with 4.8★ average rating",
            icon="phone_iphone",
            detail_page_url="/app-development",
            is_active=True,
            order=4
        ),
        Service(
            title="SEO Audit",
            description="Comprehensive audits revealing 475% traffic increase opportunities",
            icon="search",
            detail_page_url="/seo-audit",
            is_active=True,
            order=5
        ),
        Service(
            title="Project Management",
            description="Agile delivery with 98.5% success rate and on-time completion",
            icon="dashboard",
            detail_page_url="/project-management",
            is_active=True,
            order=6
        ),
        Service(
            title="Finance & Accounting",
            description="Virtual CFO and bookkeeping with 42% cost savings and 99.98% accuracy",
            icon="account_balance",
            detail_page_url="/finance-accounting",
            is_active=True,
            order=7
        ),
        Service(
            title="Content Production",
            description="Professional blog, video, and design services with 385% engagement boost",
            icon="movie_creation",
            detail_page_url="/content-production",
            is_active=True,
            order=8
        ),
        Service(
            title="Virtual Assistance",
            description="Dedicated remote support to handle administrative tasks and operations",
            icon="support_agent",
            detail_page_url="/services",
            is_active=True,
            order=9
        ),
    ])
    
    # Benefits (Why Choose Us)
    Benefit.objects.bulk_create([
        Benefit(
            title="Proven Track Record",
            description="500+ successful projects with 98% client retention rate across diverse industries",
            icon="verified",
            order=1
        ),
        Benefit(
            title="Rapid Deployment",
            description="Agile methodology ensuring 95% on-time delivery without compromising quality",
            icon="speed",
            order=2
        ),
        Benefit(
            title="Data-Driven Decisions",
            description="Every strategy backed by analytics, A/B testing, and performance metrics",
            icon="analytics",
            order=3
        ),
    ])
    
    # Guarantees
    Guarantee.objects.bulk_create([
        Guarantee(text="100% Satisfaction - Free revisions until you're completely satisfied", icon="check_circle", order=1),
        Guarantee(text="No Hidden Costs - Transparent pricing with detailed project quotations", icon="check_circle", order=2),
        Guarantee(text="Ongoing Support - 24/7 technical assistance and maintenance included", icon="check_circle", order=3),
        Guarantee(text="Measurable ROI - Performance tracking with monthly detailed reports", icon="check_circle", order=4),
    ])
    
    # Featured Case Study
    case_study = CaseStudy.objects.create(
        title="340% Traffic Growth in 6 Months",
        category="E-commerce",
        description="We developed a custom SEO engine and implemented AI-powered product recommendations that revolutionized their online presence.",
        is_featured=True,
        order=1
    )
    
    # Case Study Metrics
    CaseStudyMetric.objects.bulk_create([
        CaseStudyMetric(case_study=case_study, label="Organic Traffic", value="340%", order=1),
        CaseStudyMetric(case_study=case_study, label="Revenue Growth", value="$12M", order=2),
        CaseStudyMetric(case_study=case_study, label="Bounce Reduction", value="45%", order=3),
        CaseStudyMetric(case_study=case_study, label="Conversion Rate", value="6.8x", order=4),
    ])
    
    # Testimonial
    Testimonial.objects.create(
        client_name="Marcus Sterling",
        client_title="CEO",
        client_company="Sterling Fintech",
        quote="Techlynx Pro transformed our entire digital infrastructure. Their AI solutions reduced our operational costs by 85%, and their marketing team delivered a 3x ROI within the first year. Simply outstanding.",
        rating=5,
        is_active=True,
        order=1
    )
    
    # CTA Section
    CTASection.objects.create(
        headline="Ready to Transform Your Business?",
        description="Get a free consultation and discover how we can drive 200%+ ROI for your business",
        button_primary_text="Schedule Free Consultation",
        button_primary_url="/contact",
        button_secondary_text="+1 (520) 666-4699",
        button_secondary_url="tel:+15206664699"
    )


def reverse_populate(apps, schema_editor):
    """Remove populated data if migration is reversed"""
    HeroSection = apps.get_model('website', 'HeroSection')
    HeroBenefit = apps.get_model('website', 'HeroBenefit')
    CompanyStat = apps.get_model('website', 'CompanyStat')
    Service = apps.get_model('website', 'Service')
    Benefit = apps.get_model('website', 'Benefit')
    Guarantee = apps.get_model('website', 'Guarantee')
    CaseStudy = apps.get_model('website', 'CaseStudy')
    CaseStudyMetric = apps.get_model('website', 'CaseStudyMetric')
    Testimonial = apps.get_model('website', 'Testimonial')
    CTASection = apps.get_model('website', 'CTASection')
    
    HeroSection.objects.all().delete()
    HeroBenefit.objects.all().delete()
    CompanyStat.objects.all().delete()
    Service.objects.all().delete()
    Benefit.objects.all().delete()
    Guarantee.objects.all().delete()
    CaseStudyMetric.objects.all().delete()
    CaseStudy.objects.all().delete()
    Testimonial.objects.all().delete()
    CTASection.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_benefit_casestudy_companystat_ctasection_guarantee_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_home_content, reverse_populate),
    ]
