# Generated by Django 5.0.14 on 2026-02-10 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_populate_home_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='benefit',
            options={'ordering': ['order'], 'verbose_name': '6️⃣ Benefit', 'verbose_name_plural': '6️⃣ Benefits (Why Choose Us)'},
        ),
        migrations.AlterModelOptions(
            name='casestudy',
            options={'ordering': ['order'], 'verbose_name': '8️⃣ Case Study', 'verbose_name_plural': '8️⃣ Case Studies (Success Stories)'},
        ),
        migrations.AlterModelOptions(
            name='companystat',
            options={'ordering': ['order'], 'verbose_name': '5️⃣ Company Statistic', 'verbose_name_plural': '5️⃣ Company Statistics'},
        ),
        migrations.AlterModelOptions(
            name='ctasection',
            options={'verbose_name': '🔟 CTA Section', 'verbose_name_plural': '🔟 CTA Section (Call-to-Action)'},
        ),
        migrations.AlterModelOptions(
            name='guarantee',
            options={'ordering': ['order'], 'verbose_name': '7️⃣ Guarantee', 'verbose_name_plural': '7️⃣ Guarantees (Our Guarantees)'},
        ),
        migrations.AlterModelOptions(
            name='herobenefit',
            options={'ordering': ['order'], 'verbose_name': '2️⃣ Hero Benefit', 'verbose_name_plural': '2️⃣ Hero Benefits (Key Metrics)'},
        ),
        migrations.AlterModelOptions(
            name='herosection',
            options={'verbose_name': '1️⃣ Hero Section', 'verbose_name_plural': '1️⃣ Hero Section (Main Banner)'},
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'ordering': ['order'], 'verbose_name': '3️⃣ Partner Logo', 'verbose_name_plural': '3️⃣ Partner Logos (Trusted By)'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['order'], 'verbose_name': '4️⃣ Service', 'verbose_name_plural': '4️⃣ Services (9 Service Cards)'},
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['order'], 'verbose_name': '9️⃣ Testimonial', 'verbose_name_plural': '9️⃣ Testimonials (Client Reviews)'},
        ),
    ]
