# Generated by Django 5.0.14 on 2026-02-10 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_benefit_options_alter_casestudy_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactinquiry',
            options={'ordering': ['-created_at'], 'verbose_name': 'Contact Form Submission', 'verbose_name_plural': '📧 Contact Forms'},
        ),
        migrations.AlterModelOptions(
            name='newsletter',
            options={'ordering': ['-subscribed_at'], 'verbose_name': 'Newsletter Subscriber', 'verbose_name_plural': '📧 Newsletter Subscribers'},
        ),
    ]
