# Generated by Django 5.0.14 on 2026-02-10 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_contactinquiry_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Service name (e.g., AI Solutions)', max_length=100)),
                ('description', models.TextField(help_text='Service description paragraph')),
                ('icon', models.CharField(default='settings', help_text='Material Symbols icon name', max_length=100)),
                ('detail_page_url', models.CharField(help_text='Detail page URL (e.g., /ai-solutions)', max_length=200)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower first)')),
                ('is_active', models.BooleanField(default=True, help_text='Show on services page')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '2️⃣ Service Detail',
                'verbose_name_plural': '2️⃣ Service Details (Service Cards)',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ServicesPageCTA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='Ready to Scale Your Business?', max_length=200)),
                ('description', models.TextField(default='Get a free strategy call to explore solutions tailored to your needs')),
                ('button_text', models.CharField(default='Send Inquiry', max_length=100)),
                ('disclaimer_text', models.CharField(default='NO SPAM. ONLY SOLUTIONS.', help_text='Text below submit button', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Show/hide entire CTA section')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '6️⃣ Services CTA',
                'verbose_name_plural': '6️⃣ Services CTA Section',
            },
        ),
        migrations.CreateModel(
            name='ServicesPageHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_text', models.CharField(default='Trusted US-Based Agency', help_text='Top badge text', max_length=100)),
                ('headline', models.CharField(default='Scalable IT & Digital Marketing Solutions', max_length=200)),
                ('subheadline', models.TextField(default='High-performance expertise to help your business dominate the market')),
                ('cta_primary_text', models.CharField(default='View Our Services', max_length=100)),
                ('cta_primary_url', models.CharField(default='#services', max_length=200)),
                ('cta_secondary_text', models.CharField(default='Talk to an Expert', max_length=100)),
                ('cta_secondary_url', models.CharField(default='/contact', max_length=200)),
                ('hero_image', models.ImageField(blank=True, help_text='Hero section background image', null=True, upload_to='services/hero/')),
                ('stat_value', models.CharField(default='98%', help_text='Stat badge value (e.g., 98%)', max_length=50)),
                ('stat_label', models.CharField(default='Client Success Rate', help_text='Stat badge label', max_length=100)),
                ('stat_icon', models.CharField(default='trending_up', help_text='Material icon name for stat badge', max_length=100)),
                ('is_stat_visible', models.BooleanField(default=True, help_text='Show/hide stat badge')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '1️⃣ Services Hero',
                'verbose_name_plural': '1️⃣ Services Hero Section',
            },
        ),
        migrations.CreateModel(
            name='WhyChooseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Grid image for Why Choose section', upload_to='services/why_choose/')),
                ('alt_text', models.CharField(help_text='Image alt text for SEO', max_length=200)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower first)')),
            ],
            options={
                'verbose_name': '5️⃣ Why Choose Image',
                'verbose_name_plural': '5️⃣ Why Choose Images (Image Grid)',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WhyChooseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Benefit title (e.g., US-Based Expertise)', max_length=100)),
                ('description', models.TextField(help_text='Benefit description')),
                ('icon', models.CharField(default='verified', help_text='Material icon name', max_length=100)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower first)')),
                ('is_active', models.BooleanField(default=True, help_text='Show on services page')),
            ],
            options={
                'verbose_name': '4️⃣ Why Choose Item',
                'verbose_name_plural': '4️⃣ Why Choose Items (Benefits)',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ServiceFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_text', models.CharField(help_text='Feature bullet point text', max_length=200)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower first)')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='website.servicedetail')),
            ],
            options={
                'verbose_name': '3️⃣ Service Feature',
                'verbose_name_plural': '3️⃣ Service Features (Bullet Points)',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CTAChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Checklist item text', max_length=200)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower first)')),
                ('is_active', models.BooleanField(default=True, help_text='Show this checklist item')),
                ('cta_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='website.servicespagecta')),
            ],
            options={
                'verbose_name': '7️⃣ CTA Checklist Item',
                'verbose_name_plural': '7️⃣ CTA Checklist Items',
                'ordering': ['order'],
            },
        ),
    ]
