# Generated by Django - Data migration for Services page initial content

from django.db import migrations


def populate_services_page_data(apps, schema_editor):
    """Populate Services page with initial content from design"""
    
    # Get model classes
    ServicesPageHero = apps.get_model('website', 'ServicesPageHero')
    ServiceDetail = apps.get_model('website', 'ServiceDetail')
    ServiceFeature = apps.get_model('website', 'ServiceFeature')
    WhyChooseItem = apps.get_model('website', 'WhyChooseItem')
    ServicesPageCTA = apps.get_model('website', 'ServicesPageCTA')
    CTAChecklist = apps.get_model('website', 'CTAChecklist')
    
    # 1. Create Hero Section (Singleton)
    hero = ServicesPageHero.objects.create(
        badge_text="Trusted US-Based Agency",
        headline="Scalable IT & Digital Marketing Solutions",
        subheadline="High-performance expertise to help your business dominate the digital landscape through SEO-first methodologies.",
        cta_primary_text="View Our Services",
        cta_primary_url="#services",
        cta_secondary_text="Talk to an Expert",
        cta_secondary_url="/contact",
        stat_value="98%",
        stat_label="Client Success Rate",
        stat_icon="trending_up",
        is_stat_visible=True
    )
    
    # 2. Create Service Cards with Features
    services_data = [
        {
            'title': 'AI Solutions',
            'description': 'Intelligent AI agents and machine learning solutions that automate workflows and drive business innovation.',
            'icon': 'psychology',
            'detail_page_url': '/ai-solutions',
            'order': 1,
            'features': [
                'AI Agent Development',
                'Machine Learning Models'
            ]
        },
        {
            'title': 'Web Development',
            'description': 'Custom, high-speed, SEO-optimized websites built for high conversion rates and seamless user experiences.',
            'icon': 'code',
            'detail_page_url': '/web-development',
            'order': 2,
            'features': [
                'React & Next.js Experts',
                'E-commerce Solutions'
            ]
        },
        {
            'title': 'Digital Marketing',
            'description': 'Data-driven strategies to dominate search results, grow your brand authority, and maximize ROI on every campaign.',
            'icon': 'ads_click',
            'detail_page_url': '/digital-marketing',
            'order': 3,
            'features': [
                'Advanced SEO & SEM',
                'Content Strategy'
            ]
        },
        {
            'title': 'App Development',
            'description': 'Native and cross-platform mobile applications with intuitive design and powerful functionality.',
            'icon': 'phone_android',
            'detail_page_url': '/app-development',
            'order': 4,
            'features': [
                'iOS & Android Apps',
                'React Native & Flutter'
            ]
        },
        {
            'title': 'SEO Audit',
            'description': 'Comprehensive SEO analysis and optimization strategies to boost your search engine rankings.',
            'icon': 'search',
            'detail_page_url': '/seo-audit',
            'order': 5,
            'features': [
                'Technical SEO Analysis',
                'Keyword Research'
            ]
        },
        {
            'title': 'Project Management',
            'description': 'Strategic oversight and agile execution to deliver projects on time and within budget.',
            'icon': 'task_alt',
            'detail_page_url': '/project-management',
            'order': 6,
            'features': [
                'Agile Methodologies',
                'Risk Management'
            ]
        },
        {
            'title': 'Virtual Assistance',
            'description': 'Professional remote support services to handle administrative tasks and business operations.',
            'icon': 'support_agent',
            'detail_page_url': '/services',
            'order': 7,
            'features': [
                'Executive Assistance',
                'Customer Support'
            ]
        },
        {
            'title': 'Finance & Accounting',
            'description': 'Expert financial management services including bookkeeping, payroll, and financial reporting.',
            'icon': 'account_balance',
            'detail_page_url': '/finance-accounting',
            'order': 8,
            'features': [
                'Bookkeeping Services',
                'Financial Analysis'
            ]
        },
        {
            'title': 'Content Production',
            'description': 'Professional content creation including blogs, videos, graphics, and social media content.',
            'icon': 'movie_creation',
            'detail_page_url': '/content-production',
            'order': 9,
            'features': [
                'SEO Writing',
                'Video Production'
            ]
        }
    ]
    
    for service_data in services_data:
        features = service_data.pop('features')
        service = ServiceDetail.objects.create(
            is_active=True,
            **service_data
        )
        
        # Create features for this service
        for idx, feature_text in enumerate(features, 1):
            ServiceFeature.objects.create(
                service=service,
                feature_text=feature_text,
                order=idx
            )
    
    # 3. Create Why Choose Items
    why_choose_data = [
        {
            'title': 'US-Based Expertise',
            'description': 'Work directly with a domestic team that understands your market and goals.',
            'icon': 'public',
            'order': 1
        },
        {
            'title': 'SEO-First Approach',
            'description': 'Every line of code and piece of content is optimized for search engines from day one.',
            'icon': 'search_insights',
            'order': 2
        },
        {
            'title': 'Scalable Solutions',
            'description': 'Flexible services designed to grow alongside your business as you scale up.',
            'icon': 'bolt',
            'order': 3
        }
    ]
    
    for item_data in why_choose_data:
        WhyChooseItem.objects.create(
            is_active=True,
            **item_data
        )
    
    # 4. Create CTA Section (Singleton)
    cta_section = ServicesPageCTA.objects.create(
        heading="Ready to Scale Your Business?",
        description="Get a customized strategy consultation with our US-based technical experts.",
        button_text="Send Inquiry",
        disclaimer_text="NO SPAM. ONLY SOLUTIONS.",
        is_active=True
    )
    
    # 5. Create CTA Checklist Items
    checklist_items = [
        'Detailed technical audit included',
        'Custom growth roadmap',
        'Pricing for teams of any size'
    ]
    
    for idx, text in enumerate(checklist_items, 1):
        CTAChecklist.objects.create(
            cta_section=cta_section,
            text=text,
            order=idx,
            is_active=True
        )


def reverse_services_page_data(apps, schema_editor):
    """Remove Services page data"""
    ServicesPageHero = apps.get_model('website', 'ServicesPageHero')
    ServiceDetail = apps.get_model('website', 'ServiceDetail')
    ServiceFeature = apps.get_model('website', 'ServiceFeature')
    WhyChooseItem = apps.get_model('website', 'WhyChooseItem')
    ServicesPageCTA = apps.get_model('website', 'ServicesPageCTA')
    CTAChecklist = apps.get_model('website', 'CTAChecklist')
    
    ServicesPageHero.objects.all().delete()
    ServiceDetail.objects.all().delete()
    ServiceFeature.objects.all().delete()
    WhyChooseItem.objects.all().delete()
    ServicesPageCTA.objects.all().delete()
    CTAChecklist.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_servicedetail_servicespagecta_servicespagehero_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_services_page_data, reverse_services_page_data),
    ]
