# Generated by Django 6.0.2 on 2026-02-10 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_ctachecklist_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ctachecklist',
            options={'ordering': ['order'], 'verbose_name': '7️⃣ CTA Checklist Item', 'verbose_name_plural': '7️⃣ CTA Checklist Items'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['order'], 'verbose_name': '0️⃣ Service', 'verbose_name_plural': '0️⃣ Services (Home Page Cards)'},
        ),
        migrations.AlterModelOptions(
            name='servicedetail',
            options={'ordering': ['order'], 'verbose_name': '2️⃣ Service Detail', 'verbose_name_plural': '2️⃣ Service Details (Service Cards)'},
        ),
        migrations.AlterModelOptions(
            name='servicefeature',
            options={'ordering': ['order'], 'verbose_name': '3️⃣ Service Feature', 'verbose_name_plural': '3️⃣ Service Features (Bullet Points)'},
        ),
        migrations.AlterModelOptions(
            name='servicespagecta',
            options={'verbose_name': '6️⃣ Services CTA', 'verbose_name_plural': '6️⃣ Services CTA Section'},
        ),
        migrations.AlterModelOptions(
            name='servicespagehero',
            options={'verbose_name': '1️⃣ Services Hero', 'verbose_name_plural': '1️⃣ Services Hero Section'},
        ),
        migrations.AlterModelOptions(
            name='whychooseimage',
            options={'ordering': ['order'], 'verbose_name': '5️⃣ Why Choose Image', 'verbose_name_plural': '5️⃣ Why Choose Images (Image Grid)'},
        ),
        migrations.AlterModelOptions(
            name='whychooseitem',
            options={'ordering': ['order'], 'verbose_name': '4️⃣ Why Choose Item', 'verbose_name_plural': '4️⃣ Why Choose Items (Benefits)'},
        ),
    ]
