# Generated by Django 6.0.2 on 2026-02-10 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_alter_ctachecklist_options_alter_service_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name (e.g., Digital Marketing)', max_length=100, unique=True)),
                ('slug', models.SlugField(help_text='URL-friendly version (e.g., digital-marketing)', max_length=100, unique=True)),
                ('order', models.IntegerField(default=0, help_text='Display order in filter buttons')),
                ('is_active', models.BooleanField(default=True, help_text='Show in category filters')),
            ],
            options={
                'verbose_name': '📝 1️⃣ Blog Category',
                'verbose_name_plural': '📝 1️⃣ Blog Categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Article title', max_length=200)),
                ('slug', models.SlugField(help_text='URL slug (auto-generated from title)', max_length=200, unique=True)),
                ('excerpt', models.TextField(help_text='Short description (2-3 sentences)')),
                ('content', models.TextField(help_text='Full article content (HTML supported)')),
                ('featured_image', models.ImageField(blank=True, help_text='Article featured image', null=True, upload_to='blog/')),
                ('author', models.CharField(default='Techlynx Team', help_text='Author name', max_length=100)),
                ('read_time', models.IntegerField(default=5, help_text='Estimated reading time in minutes')),
                ('is_featured', models.BooleanField(default=False, help_text='Show as featured article on top')),
                ('is_trending', models.BooleanField(default=False, help_text='Show in trending sidebar')),
                ('trending_order', models.IntegerField(default=0, help_text='Order in trending list (1, 2, 3)')),
                ('is_published', models.BooleanField(default=True, help_text='Published and visible on blog')),
                ('published_date', models.DateField(help_text='Publication date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(help_text='Article category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='website.blogcategory')),
            ],
            options={
                'verbose_name': '📝 2️⃣ Blog Post',
                'verbose_name_plural': '📝 2️⃣ Blog Posts',
                'ordering': ['-published_date', '-created_at'],
            },
        ),
    ]
