# Generated by Django - Data migration for Blog page initial content

from django.db import migrations
from datetime import date


def populate_blog_data(apps, schema_editor):
    """Populate Blog page with initial content from design"""
    
    # Get model classes
    BlogCategory = apps.get_model('website', 'BlogCategory')
    BlogPost = apps.get_model('website', 'BlogPost')
    
    # 1. Create Blog Categories
    categories = [
        {'name': 'All Insights', 'slug': 'all-insights', 'order': 1},
        {'name': 'IT Solutions', 'slug': 'it-solutions', 'order': 2},
        {'name': 'Digital Marketing', 'slug': 'digital-marketing', 'order': 3},
        {'name': 'Talent Trends', 'slug': 'talent-trends', 'order': 4},
        {'name': 'Industry Trends', 'slug': 'industry-trends', 'order': 5},
        {'name': 'Talent Acquisition', 'slug': 'talent-acquisition', 'order': 6},
    ]
    
    category_objects = {}
    for cat_data in categories:
        category = BlogCategory.objects.create(is_active=True, **cat_data)
        category_objects[cat_data['slug']] = category
    
    # 2. Create Featured Article (Hero)
    BlogPost.objects.create(
        title="Optimizing Cloud Infrastructure for 2024 Scalability",
        slug="optimizing-cloud-infrastructure-2024-scalability",
        excerpt="Discover how Techlynx Pro is revolutionizing enterprise scalability through next-gen cloud architecture, serverless optimization, and DevOps excellence.",
        content="""<p>Cloud infrastructure continues to evolve rapidly, and 2024 brings new challenges and opportunities for businesses looking to scale efficiently.</p>
        
<p>In this comprehensive guide, we explore the latest trends in cloud architecture, serverless computing, and DevOps practices that are helping enterprises achieve unprecedented levels of scalability and performance.</p>

<h2>Key Takeaways</h2>
<ul>
<li>Serverless architecture reduces operational overhead by 70%</li>
<li>Multi-cloud strategies provide better resilience and cost optimization</li>
<li>Infrastructure as Code (IaC) enables rapid deployment and consistency</li>
<li>Container orchestration with Kubernetes scales seamlessly</li>
</ul>

<p>Our team at Techlynx Pro has helped over 100 enterprises transition to optimized cloud infrastructure, resulting in average cost savings of 40% and performance improvements of 3x.</p>""",
        category=category_objects.get('it-solutions'),
        author="Alex Sterling",
        read_time=12,
        is_featured=True,
        is_trending=False,
        is_published=True,
        published_date=date(2024, 5, 15)
    )
    
    # 3. Create Regular Blog Posts
    posts_data = [
        {
            'title': 'The ROI of Omnichannel Marketing in B2B Tech',
            'slug': 'roi-omnichannel-marketing-b2b-tech',
            'excerpt': 'Why a fragmented marketing strategy is costing your agency leads and how to unify your brand voice across touchpoints.',
            'content': '<p>Omnichannel marketing is no longer optional for B2B tech companies. Learn how to measure ROI and optimize your strategy.</p>',
            'category': 'digital-marketing',
            'author': 'Sarah Mitchell',
            'read_time': 8,
            'published_date': date(2024, 5, 12),
            'is_trending': True,
            'trending_order': 1
        },
        {
            'title': 'Closing the Tech Skills Gap in Remote Teams',
            'slug': 'closing-tech-skills-gap-remote-teams',
            'excerpt': 'Strategies for continuous upskilling and why your company culture is your biggest recruitment asset.',
            'content': '<p>Remote teams face unique challenges in skill development. Discover proven strategies to build and maintain high-performing remote tech teams.</p>',
            'category': 'talent-acquisition',
            'author': 'Michael Chen',
            'read_time': 5,
            'published_date': date(2024, 5, 10),
            'is_trending': False
        },
        {
            'title': 'Cybersecurity Best Practices for 2024',
            'slug': 'cybersecurity-best-practices-2024',
            'excerpt': 'A comprehensive guide for CTOs to secure decentralized infrastructure against evolving threats.',
            'content': '<p>Cybersecurity threats evolve constantly. Stay ahead with our comprehensive guide for CTOs and security professionals.</p>',
            'category': 'it-solutions',
            'author': 'David Park',
            'read_time': 15,
            'published_date': date(2024, 5, 5),
            'is_trending': True,
            'trending_order': 2
        },
        {
            'title': 'How Generative AI is Reshaping Tech Development',
            'slug': 'generative-ai-reshaping-tech-development',
            'excerpt': 'Exploring the balance between automated coding assistants and human architectural oversight.',
            'content': '<p>Generative AI tools are transforming how developers work. Learn how to leverage AI while maintaining code quality and architecture standards.</p>',
            'category': 'industry-trends',
            'author': 'Emily Rodriguez',
            'read_time': 10,
            'published_date': date(2024, 4, 28),
            'is_trending': False
        },
        {
            'title': 'Why SEO-First Design is Crucial for 2024 Launch',
            'slug': 'seo-first-design-crucial-2024-launch',
            'excerpt': 'Building SEO into your design process from day one delivers 300% better organic traffic results.',
            'content': '<p>SEO should never be an afterthought. Learn how to integrate SEO principles into your design process for maximum organic visibility.</p>',
            'category': 'digital-marketing',
            'author': 'Jennifer Wu',
            'read_time': 7,
            'published_date': date(2024, 5, 8),
            'is_trending': True,
            'trending_order': 3
        },
        {
            'title': 'The Rise of Fractional CTO Services for Startups',
            'slug': 'rise-fractional-cto-services-startups',
            'excerpt': 'How early-stage startups are accessing enterprise-level technical leadership without full-time costs.',
            'content': '<p>Fractional CTOs provide strategic technical leadership at a fraction of the cost. Perfect for startups and growing businesses.</p>',
            'category': 'it-solutions',
            'author': 'Robert Chang',
            'read_time': 6,
            'published_date': date(2024, 5, 3),
            'is_trending': False
        },
        {
            'title': 'Data Sovereignty and Your Cloud Infrastructure',
            'slug': 'data-sovereignty-cloud-infrastructure',
            'excerpt': 'Understanding regulatory compliance requirements for international data storage and processing.',
            'content': '<p>Data sovereignty regulations are complex and constantly evolving. Ensure your cloud infrastructure meets global compliance standards.</p>',
            'category': 'it-solutions',
            'author': 'Lisa Thompson',
            'read_time': 12,
            'published_date': date(2024, 4, 30),
            'is_trending': False
        },
    ]
    
    for post_data in posts_data:
        category_slug = post_data.pop('category')
        category = category_objects.get(category_slug)
        BlogPost.objects.create(
            category=category,
            is_published=True,
            **post_data
        )


def reverse_blog_data(apps, schema_editor):
    """Remove Blog page data"""
    BlogCategory = apps.get_model('website', 'BlogCategory')
    BlogPost = apps.get_model('website', 'BlogPost')
    
    BlogPost.objects.all().delete()
    BlogCategory.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_blogcategory_blogpost'),
    ]

    operations = [
        migrations.RunPython(populate_blog_data, reverse_blog_data),
    ]
