# Generated by Django 6.0.2 on 2026-02-10 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_blog_initial_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcategory',
            options={'ordering': ['order'], 'verbose_name': '1️⃣ Blog Category', 'verbose_name_plural': '1️⃣ Blog Categories'},
        ),
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-published_date', '-created_at'], 'verbose_name': '2️⃣ Blog Post', 'verbose_name_plural': '2️⃣ Blog Posts'},
        ),
    ]
