# Generated by Django - Data migration to add 2 more blog posts

from django.db import migrations
from datetime import date


def add_more_blog_posts(apps, schema_editor):
    """Add 2 more blog posts to the blog page"""
    
    BlogCategory = apps.get_model('website', 'BlogCategory')
    BlogPost = apps.get_model('website', 'BlogPost')
    
    # Get existing categories
    it_solutions = BlogCategory.objects.get(slug='it-solutions')
    digital_marketing = BlogCategory.objects.get(slug='digital-marketing')
    
    # Create 2 new blog posts
    posts_data = [
        {
            'title': 'Microservices Architecture: When and How to Migrate',
            'slug': 'microservices-architecture-when-how-migrate',
            'excerpt': 'Breaking down monolithic applications into microservices requires careful planning. Learn the best practices and common pitfalls to avoid.',
            'content': '''<p>Microservices architecture has become increasingly popular, but it's not a silver bullet. Understanding when and how to migrate is crucial for success.</p>

<h2>Key Considerations</h2>
<ul>
<li>Start with a clear migration strategy and timeline</li>
<li>Identify service boundaries based on business capabilities</li>
<li>Implement proper API gateway and service mesh</li>
<li>Ensure monitoring and observability from day one</li>
</ul>

<p>Our team has successfully migrated over 50 monolithic applications to microservices, reducing deployment time by 80% and improving system reliability significantly.</p>

<h2>Step-by-Step Approach</h2>
<p>Begin with the strangler pattern - gradually replacing parts of the monolith rather than a big bang rewrite. This minimizes risk and allows teams to learn as they go.</p>

<p>Proper containerization with Docker and orchestration with Kubernetes ensures your microservices can scale independently based on demand.</p>''',
            'category': it_solutions,
            'author': 'Thomas Anderson',
            'read_time': 11,
            'published_date': date(2024, 4, 25),
            'is_trending': False,
            'is_published': True
        },
        {
            'title': 'Content Marketing Strategies That Actually Convert',
            'slug': 'content-marketing-strategies-actually-convert',
            'excerpt': 'Stop creating content that no one reads. Discover data-driven strategies that turn blog visitors into qualified leads and customers.',
            'content': '''<p>Content marketing is saturated, but strategic content that addresses real pain points still delivers exceptional ROI for B2B companies.</p>

<h2>What Works in 2024</h2>
<ul>
<li>Problem-aware content that targets buyer intent keywords</li>
<li>Interactive content like calculators and assessments</li>
<li>Video tutorials and case study deep-dives</li>
<li>Thought leadership with original research and data</li>
</ul>

<p>Companies that publish consistent, high-quality content generate 3x more leads than those who don't, while spending 62% less on acquisition costs.</p>

<h2>Distribution is Everything</h2>
<p>Great content without distribution is invisible. Use a multi-channel approach: SEO, social media, email nurturing, and strategic partnerships to amplify reach.</p>

<p>Track metrics that matter: time on page, scroll depth, conversion rates, and lead quality - not just vanity metrics like page views.</p>''',
            'category': digital_marketing,
            'author': 'Rachel Martinez',
            'read_time': 9,
            'published_date': date(2024, 4, 22),
            'is_trending': False,
            'is_published': True
        },
    ]
    
    for post_data in posts_data:
        BlogPost.objects.create(**post_data)


def reverse_blog_posts(apps, schema_editor):
    """Remove the 2 blog posts"""
    BlogPost = apps.get_model('website', 'BlogPost')
    
    BlogPost.objects.filter(slug__in=[
        'microservices-architecture-when-how-migrate',
        'content-marketing-strategies-actually-convert'
    ]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_update_blog_verbose_names'),
    ]

    operations = [
        migrations.RunPython(add_more_blog_posts, reverse_blog_posts),
    ]
