# Generated by Django 6.0.2 on 2026-02-10 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_add_two_more_blog_posts'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareersHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_text', models.CharField(default='Now Hiring: 12 Open Roles', help_text='Hero badge text', max_length=100)),
                ('headline', models.TextField(default='Build the Future or Become the Face', help_text='Main headline (HTML tags supported for styling)')),
                ('subheadline', models.TextField(default='Join our elite team of developers and marketers driving global innovation, or receive world-class management for your talent brand.', help_text='Hero subtitle')),
                ('cta_primary_text', models.CharField(default='View Open Roles', max_length=50)),
                ('cta_primary_url', models.CharField(default='#open-roles', max_length=200)),
                ('cta_secondary_text', models.CharField(default='Get Represented', max_length=50)),
                ('cta_secondary_url', models.CharField(default='#talent-services', max_length=200)),
                ('hero_image', models.ImageField(blank=True, help_text='Hero section image', null=True, upload_to='careers/')),
                ('testimonial_text', models.TextField(default='Working here felt like joining a family of geniuses.', help_text='Testimonial quote')),
                ('testimonial_author', models.CharField(default='Sarah J., Senior Fullstack Engineer', help_text='Testimonial author name and title', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '1️⃣ Careers Hero',
                'verbose_name_plural': '1️⃣ Careers Hero',
            },
        ),
        migrations.CreateModel(
            name='CareersStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='Stat number (e.g., 50+, 12M+)', max_length=20)),
                ('label', models.CharField(help_text='Stat label/description', max_length=100)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '2️⃣ Career Stat',
                'verbose_name_plural': '2️⃣ Career Stats',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='JobDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '3️⃣ Job Department',
                'verbose_name_plural': '3️⃣ Job Departments',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='JobLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '4️⃣ Job Location',
                'verbose_name_plural': '4️⃣ Job Locations',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TalentFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(help_text='Material icon name (e.g., handshake)', max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '7️⃣ Talent Feature',
                'verbose_name_plural': '7️⃣ Talent Features',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TalentManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(default='Scale Your Personal Brand Beyond Limits', max_length=200)),
                ('description', models.TextField(default="We represent the next generation of culture-shapers. Our managers don't just find deals; they build legacies through strategic PR, legal protection, and blue-chip brand partnerships.")),
                ('cta_text', models.CharField(default='Apply for Representation', max_length=50)),
                ('cta_url', models.CharField(default='#application-form', max_length=200)),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='talent/')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='talent/')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='talent/')),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='talent/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '6️⃣ Talent Management',
                'verbose_name_plural': '6️⃣ Talent Management',
            },
        ),
        migrations.CreateModel(
            name='JobOpening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Job title', max_length=200)),
                ('slug', models.SlugField(help_text='URL slug (auto-generated from title)', max_length=200, unique=True)),
                ('job_type', models.CharField(choices=[('full-time', 'Full-time'), ('part-time', 'Part-time'), ('contract', 'Contract'), ('internship', 'Internship')], default='full-time', max_length=20)),
                ('salary_range', models.CharField(blank=True, help_text='e.g., $140k - $180k or $70k + Commission', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Full job description')),
                ('requirements', models.TextField(blank=True, help_text='Job requirements')),
                ('application_url', models.URLField(blank=True, help_text='External application URL')),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('is_active', models.BooleanField(default=True, help_text='Show on careers page')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='website.jobdepartment')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='website.joblocation')),
            ],
            options={
                'verbose_name': '5️⃣ Job Opening',
                'verbose_name_plural': '5️⃣ Job Openings',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
