# Generated by Django 6.0.2 on 2026-02-10 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_populate_careers_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('application_type', models.CharField(choices=[('job', 'Joining the Tech/Marketing Team'), ('talent', 'Talent Representation')], max_length=20)),
                ('links', models.TextField(blank=True, help_text='Portfolio/Social media links')),
                ('resume', models.FileField(blank=True, help_text='Resume or media kit', null=True, upload_to='applications/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_position', models.ForeignKey(blank=True, help_text='Applied job position (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.jobopening')),
            ],
            options={
                'verbose_name': '8️⃣ Career Application',
                'verbose_name_plural': '8️⃣ Career Applications',
                'ordering': ['-created_at'],
            },
        ),
    ]
