# Generated by Django 6.0.2 on 2026-02-10 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_careerapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, help_text='Service card image (preferred over icon)', null=True, upload_to='services/'),
        ),
        migrations.AddField(
            model_name='servicedetail',
            name='image',
            field=models.ImageField(blank=True, help_text='Service card image (preferred over icon)', null=True, upload_to='services/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='detail_page_url',
            field=models.CharField(help_text='URL slug (e.g., /services/ai-solutions/)', max_length=200),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(default='settings', help_text='Material icon name (fallback if no image)', max_length=100),
        ),
        migrations.AlterField(
            model_name='servicedetail',
            name='detail_page_url',
            field=models.CharField(help_text='Detail page URL (e.g., /services/ai-solutions/)', max_length=200),
        ),
        migrations.AlterField(
            model_name='servicedetail',
            name='icon',
            field=models.CharField(default='settings', help_text='Material Symbols icon name (fallback if no image)', max_length=100),
        ),
    ]
