# Generated by Django 6.0.2 on 2026-02-13 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_service_image_servicedetail_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIImplementationStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '🤖 Implementation Step',
                'verbose_name_plural': '🤖 Implementation Steps',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AIPerformanceMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(max_length=100)),
                ('percentage', models.IntegerField(help_text='Value between 0-100')),
                ('color', models.CharField(default='green-400', help_text='Tailwind color class (e.g., green-400, blue-500)', max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '🤖 Performance Metric',
                'verbose_name_plural': '🤖 Performance Metrics',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AIROIMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(help_text='Material icon name', max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '🤖 ROI Metric',
                'verbose_name_plural': '🤖 ROI Metrics',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AIService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(help_text='Material icon name', max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('feature_1', models.CharField(max_length=200)),
                ('feature_2', models.CharField(max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '🤖 AI Service',
                'verbose_name_plural': '🤖 AI Services',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AISolutionsCTA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.TextField(default='Ready to Harness the Power of AI?')),
                ('description', models.TextField(default='Join forward-thinking enterprises who are gaining competitive advantage through intelligent automation and AI-driven decision making.')),
                ('cta_primary_text', models.CharField(default='Start Your AI Journey', max_length=100)),
                ('cta_primary_url', models.CharField(default='/contact', max_length=200)),
                ('cta_secondary_text', models.CharField(default='Schedule Demo', max_length=100)),
                ('cta_secondary_url', models.CharField(default='/contact', max_length=200)),
                ('footer_text', models.CharField(default='Free AI readiness assessment included with every consultation.', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '🤖 AI CTA Section',
                'verbose_name_plural': '🤖 AI CTA Section',
            },
        ),
        migrations.CreateModel(
            name='AISolutionsHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_icon', models.CharField(default='psychology', help_text='Material icon name', max_length=100)),
                ('badge_text', models.CharField(default='Next-Gen AI Technology', max_length=100)),
                ('headline', models.TextField(default='Transform Your Business with AI-Powered Intelligence')),
                ('description', models.TextField(default='From intelligent chatbots to predictive analytics and machine learning models. We build custom AI solutions that automate workflows, enhance decision-making, and drive exponential growth.')),
                ('cta_primary_text', models.CharField(default='Start AI Transformation', max_length=100)),
                ('cta_primary_url', models.CharField(default='/contact', max_length=200)),
                ('cta_secondary_text', models.CharField(default='View AI Case Studies', max_length=100)),
                ('cta_secondary_url', models.CharField(default='/case-studies', max_length=200)),
                ('metric_title', models.CharField(default='AI Impact Forecast', max_length=100)),
                ('metric_main', models.CharField(default='85% Cost Reduction', max_length=100)),
                ('automation_rate', models.IntegerField(default=94, help_text='Percentage')),
                ('time_saved', models.CharField(default='2,400h/mo', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '🤖 AI Hero Section',
                'verbose_name_plural': '🤖 AI Hero Section',
            },
        ),
        migrations.CreateModel(
            name='AITechnology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('logo', models.ImageField(help_text='SVG or PNG logo (preferably SVG)', upload_to='services/ai_technologies/')),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '🤖 AI Technology',
                'verbose_name_plural': '🤖 AI Technologies',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AITechnologyDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(help_text='Material icon name', max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '🤖 AI Tech Detail',
                'verbose_name_plural': '🤖 AI Tech Details',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AITestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200)),
                ('client_position', models.CharField(max_length=200)),
                ('client_company', models.CharField(max_length=200)),
                ('client_photo', models.ImageField(blank=True, null=True, upload_to='testimonials/ai/')),
                ('testimonial_text', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '🤖 AI Testimonial',
                'verbose_name_plural': '🤖 AI Testimonials',
                'ordering': ['order'],
            },
        ),
    ]
