# Generated by Django 6.0.2 on 2026-02-13 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_add_ai_solutions_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiservice',
            name='icon_image',
            field=models.ImageField(blank=True, help_text='Service icon image (SVG/PNG preferred)', null=True, upload_to='services/ai_services/'),
        ),
        migrations.AlterField(
            model_name='aiservice',
            name='icon',
            field=models.CharField(help_text='Material icon name (fallback)', max_length=100),
        ),
    ]
