# Generated by Django 6.0.2 on 2026-02-13 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_add_ai_service_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='aitechnologydetail',
            name='icon_image',
            field=models.ImageField(blank=True, help_text='Technology icon image (SVG/PNG preferred)', null=True, upload_to='services/ai_tech_details/'),
        ),
        migrations.AlterField(
            model_name='aitechnologydetail',
            name='icon',
            field=models.CharField(help_text='Material icon name (fallback)', max_length=100),
        ),
    ]
