# Generated by Django 6.0.2 on 2026-02-13 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_add_tech_detail_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='airoimetric',
            name='icon_image',
            field=models.ImageField(blank=True, help_text='ROI metric icon image (SVG/PNG preferred)', null=True, upload_to='services/ai_roi_metrics/'),
        ),
        migrations.AlterField(
            model_name='airoimetric',
            name='icon',
            field=models.CharField(help_text='Material icon name (fallback)', max_length=100),
        ),
    ]
