# Generated by Django 6.0.2 on 2026-02-13 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_add_roi_metric_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebDevCTA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.TextField(default='Ready to Scale Your Online Presence?')),
                ('description', models.TextField(default='Join dozens of US enterprises who have transformed their digital ROI with our SEO-first development approach.')),
                ('cta_primary_text', models.CharField(default='Book Free Consultation', max_length=100)),
                ('cta_primary_url', models.CharField(default='/contact', max_length=200)),
                ('cta_secondary_text', models.CharField(default='Contact Sales', max_length=100)),
                ('cta_secondary_url', models.CharField(default='/contact', max_length=200)),
                ('footer_text', models.CharField(default='No credit card required. Initial consult is 100% free.', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '🌐 Web Dev CTA',
                'verbose_name_plural': '🌐 Web Dev CTA',
            },
        ),
        migrations.CreateModel(
            name='WebDevHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_text', models.CharField(default='US-Based Enterprise Agency', max_length=200)),
                ('headline', models.TextField(default="Scalable, <span class='text-primary'>SEO-First</span> Web Development")),
                ('description', models.TextField(default='High-performance websites built with Next.js and WordPress to drive ROI. Get a future-proof digital presence that converts visitors into loyal customers.')),
                ('cta_primary_text', models.CharField(default='Book a Free Consultation', max_length=100)),
                ('cta_primary_url', models.CharField(default='/contact', max_length=200)),
                ('cta_secondary_text', models.CharField(default='View Case Studies', max_length=100)),
                ('cta_secondary_url', models.CharField(default='/case-studies', max_length=200)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='services/web_dev/hero/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '🌐 Web Dev Hero',
                'verbose_name_plural': '🌐 Web Dev Hero',
            },
        ),
        migrations.CreateModel(
            name='WebDevProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '🌐 Process Step',
                'verbose_name_plural': '🌐 Process Steps',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WebDevSEOBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(help_text='Material icon name (fallback)', max_length=100)),
                ('icon_image', models.ImageField(blank=True, null=True, upload_to='services/web_dev/seo_icons/')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '🌐 SEO Benefit',
                'verbose_name_plural': '🌐 SEO Benefits',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WebDevSEOMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(max_length=100)),
                ('score', models.IntegerField(help_text='Score out of 100')),
                ('color', models.CharField(default='green-400', help_text='Tailwind color class', max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '🌐 SEO Metric',
                'verbose_name_plural': '🌐 SEO Metrics',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WebDevService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(help_text='Material icon name (fallback)', max_length=100)),
                ('icon_image', models.ImageField(blank=True, null=True, upload_to='services/web_dev/service_icons/')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('feature_1', models.CharField(max_length=200)),
                ('feature_2', models.CharField(max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '🌐 Web Dev Service',
                'verbose_name_plural': '🌐 Web Dev Services',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WebDevStackFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(help_text='Material icon name (fallback)', max_length=100)),
                ('icon_image', models.ImageField(blank=True, null=True, upload_to='services/web_dev/stack_icons/')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '🌐 Stack Feature',
                'verbose_name_plural': '🌐 Stack Features',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WebDevTechnology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(help_text='SVG or PNG logo', upload_to='services/web_dev/tech_logos/')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '🌐 Technology',
                'verbose_name_plural': '🌐 Technologies',
                'ordering': ['order'],
            },
        ),
    ]
