# Generated by Django 6.0.2 on 2026-02-13 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_add_web_dev_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalMarketingCTA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='insights', max_length=100)),
                ('headline', models.TextField(default='Ready to see these results for yourself?')),
                ('description', models.TextField(default="Schedule a 15-minute strategy call and we'll show you exactly how we'd grow your specific brand.")),
                ('cta_text', models.CharField(default='Book Your Free Strategy Call', max_length=100)),
                ('cta_url', models.CharField(default='/contact', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '📈 Marketing CTA',
                'verbose_name_plural': '📈 Marketing CTA',
            },
        ),
        migrations.CreateModel(
            name='DigitalMarketingHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_text', models.CharField(default='ROI-Focused Growth', max_length=200)),
                ('badge_icon', models.CharField(default='trending_up', max_length=100)),
                ('headline', models.TextField(default="Scale Your Business with <span class='text-primary'>Strategy-First</span> Marketing")),
                ('description', models.TextField(default='High-performance, SEO-first digital growth services designed for measurable ROI. We help US-based brands dominate their niche through data-backed execution.')),
                ('cta_primary_text', models.CharField(default='Start Your Growth Journey', max_length=100)),
                ('cta_primary_url', models.CharField(default='/contact', max_length=200)),
                ('cta_secondary_text', models.CharField(default='View Case Studies', max_length=100)),
                ('cta_secondary_url', models.CharField(default='/case-studies', max_length=200)),
                ('growth_percentage', models.IntegerField(default=248, help_text='Revenue growth percentage')),
                ('avg_cpc_reduction', models.DecimalField(decimal_places=2, default=1.45, max_digits=5)),
                ('conversion_rate', models.DecimalField(decimal_places=1, default=8.4, max_digits=4)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '📈 Digital Marketing Hero',
                'verbose_name_plural': '📈 Digital Marketing Hero',
            },
        ),
        migrations.CreateModel(
            name='DigitalMarketingMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('growth_indicator', models.CharField(help_text='e.g., +12%, +$42k, 4.2x', max_length=100)),
                ('chart_data', models.CharField(default='20,35,30,50,85', help_text='Comma-separated percentages for 5 bars', max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '📈 Growth Metric',
                'verbose_name_plural': '📈 Growth Metrics',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='DigitalMarketingService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(help_text='Material icon name (fallback)', max_length=100)),
                ('icon_image', models.ImageField(blank=True, null=True, upload_to='services/digital_marketing/service_icons/')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('feature_1', models.CharField(max_length=200)),
                ('feature_2', models.CharField(max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '📈 Marketing Service',
                'verbose_name_plural': '📈 Marketing Services',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='DigitalMarketingStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '📈 Strategy Step',
                'verbose_name_plural': '📈 Strategy Steps',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='DigitalMarketingTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200)),
                ('client_position', models.CharField(max_length=200)),
                ('client_company', models.CharField(blank=True, max_length=200)),
                ('client_photo', models.ImageField(blank=True, null=True, upload_to='testimonials/digital_marketing/')),
                ('testimonial_text', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '📈 Marketing Testimonial',
                'verbose_name_plural': '📈 Marketing Testimonials',
                'ordering': ['order'],
            },
        ),
    ]
