# Generated by Django 6.0.2 on 2026-02-13 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_add_digital_marketing_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppDevCTA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.TextField()),
                ('description', models.TextField()),
                ('cta_primary_text', models.CharField(max_length=100)),
                ('cta_primary_url', models.CharField(max_length=200)),
                ('cta_secondary_text', models.CharField(max_length=100)),
                ('cta_secondary_url', models.CharField(max_length=200)),
                ('footer_text', models.CharField(blank=True, max_length=300)),
                ('footer_icon', models.CharField(default='verified_user', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'App Dev CTA Section',
                'verbose_name_plural': 'App Dev CTA Sections',
            },
        ),
        migrations.CreateModel(
            name='AppDevFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='security', max_length=50)),
                ('icon_image', models.ImageField(blank=True, null=True, upload_to='services/app_development/feature_icons/')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'App Dev Feature',
                'verbose_name_plural': 'App Dev Features',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AppDevHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_icon', models.CharField(default='phone_android', max_length=50)),
                ('badge_text', models.CharField(default='Native & Cross-Platform Apps', max_length=100)),
                ('headline', models.TextField()),
                ('description', models.TextField()),
                ('cta_primary_text', models.CharField(max_length=100)),
                ('cta_primary_url', models.CharField(max_length=200)),
                ('cta_secondary_text', models.CharField(max_length=100)),
                ('cta_secondary_url', models.CharField(max_length=200)),
                ('engagement_growth', models.IntegerField(default=320, help_text='User engagement growth percentage')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'App Dev Hero Section',
                'verbose_name_plural': 'App Dev Hero Sections',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AppDevPerformanceMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('value', models.CharField(help_text="e.g., '<2s', '99.8%', '68%', '4.7★'", max_length=50)),
                ('percentage', models.IntegerField(help_text='Width percentage for progress bar (0-100)')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'App Dev Performance Metric',
                'verbose_name_plural': 'App Dev Performance Metrics',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AppDevProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'App Dev Process Step',
                'verbose_name_plural': 'App Dev Process Steps',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AppDevService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='phone_android', max_length=50)),
                ('icon_image', models.ImageField(blank=True, null=True, upload_to='services/app_development/service_icons/')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('feature_1', models.CharField(max_length=200)),
                ('feature_2', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'App Dev Service',
                'verbose_name_plural': 'App Dev Services',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AppDevStackFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='phone_android', max_length=50)),
                ('icon_image', models.ImageField(blank=True, null=True, upload_to='services/app_development/stack_icons/')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'App Dev Stack Feature',
                'verbose_name_plural': 'App Dev Stack Features',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AppDevTechnology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='services/app_development/tech_logos/')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'App Dev Technology',
                'verbose_name_plural': 'App Dev Technologies',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AppDevTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200)),
                ('client_position', models.CharField(max_length=200)),
                ('client_company', models.CharField(max_length=200)),
                ('client_photo', models.ImageField(blank=True, null=True, upload_to='testimonials/app_development/')),
                ('testimonial_text', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'App Dev Testimonial',
                'verbose_name_plural': 'App Dev Testimonials',
                'ordering': ['order'],
            },
        ),
    ]
