# Generated by Django 6.0.2 on 2026-02-13 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_add_app_dev_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEOAuditBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(help_text='Material icon name', max_length=50)),
                ('icon_image', models.ImageField(blank=True, null=True, upload_to='services/seo_audit/benefit_icons/')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'SEO Audit Benefit',
                'verbose_name_plural': 'SEO Audit Benefits',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SEOAuditCTA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.TextField()),
                ('description', models.TextField()),
                ('cta_primary_text', models.CharField(max_length=100)),
                ('cta_primary_url', models.CharField(max_length=200)),
                ('cta_secondary_text', models.CharField(max_length=100)),
                ('cta_secondary_url', models.CharField(max_length=200)),
                ('footer_text', models.CharField(blank=True, max_length=300)),
                ('footer_icon', models.CharField(default='verified_user', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'SEO Audit CTA Section',
                'verbose_name_plural': 'SEO Audit CTA Sections',
            },
        ),
        migrations.CreateModel(
            name='SEOAuditHealthMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('score', models.IntegerField(help_text='Score out of 100')),
                ('percentage', models.IntegerField(help_text='Percentage for progress bar (0-100)')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'SEO Health Metric',
                'verbose_name_plural': 'SEO Health Metrics',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SEOAuditHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_icon', models.CharField(default='search', max_length=50)),
                ('badge_text', models.CharField(max_length=100)),
                ('headline', models.TextField()),
                ('description', models.TextField()),
                ('cta_primary_text', models.CharField(max_length=100)),
                ('cta_primary_url', models.CharField(default='/contact/', max_length=200)),
                ('cta_secondary_text', models.CharField(max_length=100)),
                ('cta_secondary_url', models.CharField(default='/case-studies/', max_length=200)),
                ('traffic_growth', models.IntegerField(help_text='Traffic growth percentage (e.g., 475)')),
                ('domain_authority', models.IntegerField(help_text='Domain Authority number (e.g., 68)')),
                ('keywords_ranked', models.IntegerField(help_text='Number of keywords ranked (e.g., 1247)')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'SEO Audit Hero',
                'verbose_name_plural': 'SEO Audit Hero',
            },
        ),
        migrations.CreateModel(
            name='SEOAuditProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'SEO Audit Process',
                'verbose_name_plural': 'SEO Audit Process Steps',
                'ordering': ['step_number'],
            },
        ),
        migrations.CreateModel(
            name='SEOAuditResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.TextField()),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'SEO Audit Result Section',
                'verbose_name_plural': 'SEO Audit Result Section',
            },
        ),
        migrations.CreateModel(
            name='SEOAuditService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(help_text='Material icon name', max_length=50)),
                ('icon_image', models.ImageField(blank=True, null=True, upload_to='services/seo_audit/service_icons/')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('feature_1', models.CharField(max_length=200)),
                ('feature_2', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'SEO Audit Service',
                'verbose_name_plural': 'SEO Audit Services',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SEOAuditTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200)),
                ('client_position', models.CharField(max_length=200)),
                ('client_company', models.CharField(max_length=200)),
                ('client_photo', models.ImageField(blank=True, null=True, upload_to='testimonials/seo_audit/')),
                ('testimonial_text', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'SEO Audit Testimonial',
                'verbose_name_plural': 'SEO Audit Testimonials',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SEOAuditTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(help_text='Material icon name', max_length=50)),
                ('icon_image', models.ImageField(blank=True, null=True, upload_to='services/seo_audit/tool_icons/')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'SEO Audit Tool',
                'verbose_name_plural': 'SEO Audit Tools',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SEOAuditToolLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='services/seo_audit/tool_logos/')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'SEO Tool Logo',
                'verbose_name_plural': 'SEO Tool Logos',
                'ordering': ['order'],
            },
        ),
    ]
