# Generated by Django 6.0.2 on 2026-02-13 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_seoauditbenefit_seoauditcta_seoaudithealthmetric_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PMBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(help_text='Material icon name', max_length=50)),
                ('icon_image', models.ImageField(blank=True, null=True, upload_to='services/project_management/benefit_icons/')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'PM Benefit',
                'verbose_name_plural': 'PM Benefits',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PMCTA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.TextField()),
                ('description', models.TextField()),
                ('cta_primary_text', models.CharField(max_length=100)),
                ('cta_primary_url', models.CharField(max_length=200)),
                ('cta_secondary_text', models.CharField(max_length=100)),
                ('cta_secondary_url', models.CharField(max_length=200)),
                ('footer_text', models.CharField(blank=True, max_length=300)),
                ('footer_icon', models.CharField(default='verified_user', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'PM CTA Section',
                'verbose_name_plural': 'PM CTA Sections',
            },
        ),
        migrations.CreateModel(
            name='PMHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_icon', models.CharField(default='task_alt', max_length=50)),
                ('badge_text', models.CharField(max_length=100)),
                ('headline', models.TextField()),
                ('description', models.TextField()),
                ('cta_primary_text', models.CharField(max_length=100)),
                ('cta_primary_url', models.CharField(default='/contact/', max_length=200)),
                ('cta_secondary_text', models.CharField(max_length=100)),
                ('cta_secondary_url', models.CharField(default='/case-studies/', max_length=200)),
                ('success_rate', models.DecimalField(decimal_places=1, help_text='e.g., 98.5', max_digits=4)),
                ('ontime_delivery', models.IntegerField(help_text='Percentage (e.g., 95)')),
                ('under_budget', models.IntegerField(help_text='Percentage (e.g., 18)')),
                ('client_rating', models.DecimalField(decimal_places=1, help_text='e.g., 4.9', max_digits=2)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'PM Hero',
                'verbose_name_plural': 'PM Hero',
            },
        ),
        migrations.CreateModel(
            name='PMMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('value', models.CharField(help_text='e.g., 95%, 4.9/5.0', max_length=50)),
                ('percentage', models.IntegerField(help_text='For progress bar (0-100)')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'PM Metric',
                'verbose_name_plural': 'PM Metrics',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PMProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'PM Process',
                'verbose_name_plural': 'PM Process Steps',
                'ordering': ['step_number'],
            },
        ),
        migrations.CreateModel(
            name='PMService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(help_text='Material icon name', max_length=50)),
                ('icon_image', models.ImageField(blank=True, null=True, upload_to='services/project_management/service_icons/')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('feature_1', models.CharField(max_length=200)),
                ('feature_2', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'PM Service',
                'verbose_name_plural': 'PM Services',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PMTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200)),
                ('client_position', models.CharField(max_length=200)),
                ('client_company', models.CharField(max_length=200)),
                ('client_photo', models.ImageField(blank=True, null=True, upload_to='testimonials/project_management/')),
                ('testimonial_text', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'PM Testimonial',
                'verbose_name_plural': 'PM Testimonials',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PMTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(help_text='Material icon name', max_length=50)),
                ('icon_image', models.ImageField(blank=True, null=True, upload_to='services/project_management/tool_icons/')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'PM Tool',
                'verbose_name_plural': 'PM Tools',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PMToolLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='services/project_management/tool_logos/')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'PM Tool Logo',
                'verbose_name_plural': 'PM Tool Logos',
                'ordering': ['order'],
            },
        ),
    ]
