# Generated by Django 6.0.2 on 2026-02-15 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0026_pmbenefit_pmcta_pmhero_pmmetric_pmprocess_pmservice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VABenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(help_text='Material icon name', max_length=50)),
                ('icon_image', models.FileField(blank=True, help_text='SVG icon file', null=True, upload_to='services/virtual_assistance/benefit_icons/')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('color_scheme', models.CharField(choices=[('purple', 'Purple'), ('blue', 'Blue'), ('green', 'Green'), ('orange', 'Orange')], default='purple', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'VA Benefit',
                'verbose_name_plural': 'VA Benefits',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='VACTA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('cta_primary_text', models.CharField(max_length=100)),
                ('cta_primary_url', models.CharField(default='/contact/', max_length=200)),
                ('cta_secondary_text', models.CharField(max_length=100)),
                ('cta_secondary_url', models.CharField(default='/case-studies/', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'VA CTA',
                'verbose_name_plural': 'VA CTA',
            },
        ),
        migrations.CreateModel(
            name='VAHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_icon', models.CharField(default='support_agent', max_length=50)),
                ('badge_text', models.CharField(max_length=100)),
                ('headline', models.TextField()),
                ('description', models.TextField()),
                ('cta_primary_text', models.CharField(max_length=100)),
                ('cta_primary_url', models.CharField(default='/contact/', max_length=200)),
                ('cta_secondary_text', models.CharField(max_length=100)),
                ('cta_secondary_url', models.CharField(default='#services', max_length=200)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='services/virtual_assistance/')),
                ('tasks_completed', models.IntegerField(help_text='Total tasks completed (e.g., 500)')),
                ('support_availability', models.CharField(default='24/7', max_length=50)),
                ('satisfaction_rate', models.IntegerField(help_text='Percentage (e.g., 98)')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'VA Hero',
                'verbose_name_plural': 'VA Hero',
            },
        ),
        migrations.CreateModel(
            name='VAService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(help_text='Material icon name', max_length=50)),
                ('icon_image', models.FileField(blank=True, help_text='SVG icon file', null=True, upload_to='services/virtual_assistance/service_icons/')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('feature_1', models.CharField(max_length=200)),
                ('feature_2', models.CharField(max_length=200)),
                ('feature_3', models.CharField(max_length=200)),
                ('feature_4', models.CharField(max_length=200)),
                ('color_scheme', models.CharField(choices=[('purple', 'Purple'), ('blue', 'Blue'), ('green', 'Green'), ('orange', 'Orange')], default='purple', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'VA Service',
                'verbose_name_plural': 'VA Services',
                'ordering': ['order'],
            },
        ),
    ]
