# Generated by Django 6.0.2 on 2026-02-15 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0027_vabenefit_vacta_vahero_vaservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='FABenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(help_text='Material icon name', max_length=50)),
                ('icon_image', models.FileField(blank=True, help_text='SVG icon file', null=True, upload_to='services/finance_accounting/benefit_icons/')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('metric', models.CharField(help_text='e.g., 42% Cost Reduction', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'FA Benefit',
                'verbose_name_plural': 'FA Benefits',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FACTA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('cta_primary_text', models.CharField(max_length=100)),
                ('cta_primary_url', models.CharField(default='/contact/', max_length=200)),
                ('cta_secondary_text', models.CharField(max_length=100)),
                ('cta_secondary_url', models.CharField(default='/contact/', max_length=200)),
                ('guarantee_text', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'FA CTA',
                'verbose_name_plural': 'FA CTA',
            },
        ),
        migrations.CreateModel(
            name='FAHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_icon', models.CharField(default='account_balance', max_length=50)),
                ('badge_text', models.CharField(max_length=100)),
                ('headline', models.TextField()),
                ('description', models.TextField()),
                ('cta_primary_text', models.CharField(max_length=100)),
                ('cta_primary_url', models.CharField(default='/contact/', max_length=200)),
                ('cta_secondary_text', models.CharField(max_length=100)),
                ('cta_secondary_url', models.CharField(default='/case-studies/', max_length=200)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='services/finance_accounting/')),
                ('cost_savings_percentage', models.IntegerField(help_text='Cost savings percentage (e.g., 42)')),
                ('time_saved_monthly', models.IntegerField(help_text='Hours saved monthly (e.g., 280)')),
                ('error_rate', models.FloatField(help_text='Error rate percentage (e.g., 0.02)')),
                ('compliance_guarantee', models.CharField(default='100% Compliance Guarantee', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'FA Hero',
                'verbose_name_plural': 'FA Hero',
            },
        ),
        migrations.CreateModel(
            name='FAProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'FA Process',
                'verbose_name_plural': 'FA Process Steps',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FAService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(help_text='Material icon name', max_length=50)),
                ('icon_image', models.FileField(blank=True, help_text='SVG icon file', null=True, upload_to='services/finance_accounting/service_icons/')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('feature_1', models.CharField(max_length=200)),
                ('feature_2', models.CharField(max_length=200)),
                ('feature_3', models.CharField(blank=True, max_length=200, null=True)),
                ('feature_4', models.CharField(blank=True, max_length=200, null=True)),
                ('color_scheme', models.CharField(choices=[('purple', 'Purple'), ('blue', 'Blue'), ('green', 'Green'), ('orange', 'Orange')], default='blue', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'FA Service',
                'verbose_name_plural': 'FA Services',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FATestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200)),
                ('client_position', models.CharField(max_length=100)),
                ('client_company', models.CharField(max_length=200)),
                ('client_photo', models.ImageField(blank=True, null=True, upload_to='testimonials/finance_accounting/')),
                ('testimonial_text', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'FA Testimonial',
                'verbose_name_plural': 'FA Testimonials',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FATool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(help_text='Material icon name', max_length=50)),
                ('icon_image', models.FileField(blank=True, help_text='SVG icon file', null=True, upload_to='services/finance_accounting/tool_icons/')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(help_text='e.g., Cloud Accounting Platforms', max_length=100)),
                ('description', models.TextField()),
                ('color_scheme', models.CharField(choices=[('purple', 'Purple'), ('blue', 'Blue'), ('green', 'Green'), ('orange', 'Orange')], default='blue', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'FA Tool',
                'verbose_name_plural': 'FA Tools',
                'ordering': ['order'],
            },
        ),
    ]
