# Generated by Django 6.0.2 on 2026-02-15 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0028_fabenefit_facta_fahero_faprocess_faservice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airoimetric',
            name='icon_image',
            field=models.FileField(blank=True, help_text='SVG icon file', null=True, upload_to='services/ai_roi_metrics/'),
        ),
        migrations.AlterField(
            model_name='aiservice',
            name='icon_image',
            field=models.FileField(blank=True, help_text='SVG icon file', null=True, upload_to='services/ai_services/'),
        ),
        migrations.AlterField(
            model_name='aitechnologydetail',
            name='icon_image',
            field=models.FileField(blank=True, help_text='SVG icon file', null=True, upload_to='services/ai_tech_details/'),
        ),
        migrations.AlterField(
            model_name='appdevfeature',
            name='icon_image',
            field=models.FileField(blank=True, help_text='SVG icon file', null=True, upload_to='services/app_development/feature_icons/'),
        ),
        migrations.AlterField(
            model_name='appdevservice',
            name='icon_image',
            field=models.FileField(blank=True, help_text='SVG icon file', null=True, upload_to='services/app_development/service_icons/'),
        ),
        migrations.AlterField(
            model_name='appdevstackfeature',
            name='icon_image',
            field=models.FileField(blank=True, help_text='SVG icon file', null=True, upload_to='services/app_development/stack_icons/'),
        ),
        migrations.AlterField(
            model_name='appdevtechnology',
            name='logo',
            field=models.FileField(blank=True, help_text='SVG logo file', null=True, upload_to='services/app_development/tech_logos/'),
        ),
        migrations.AlterField(
            model_name='digitalmarketingservice',
            name='icon_image',
            field=models.FileField(blank=True, help_text='SVG icon file', null=True, upload_to='services/digital_marketing/service_icons/'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='logo',
            field=models.FileField(help_text='Partner SVG logo file', upload_to='partners/'),
        ),
        migrations.AlterField(
            model_name='pmbenefit',
            name='icon_image',
            field=models.FileField(blank=True, help_text='SVG icon file', null=True, upload_to='services/project_management/benefit_icons/'),
        ),
        migrations.AlterField(
            model_name='pmservice',
            name='icon_image',
            field=models.FileField(blank=True, help_text='SVG icon file', null=True, upload_to='services/project_management/service_icons/'),
        ),
        migrations.AlterField(
            model_name='pmtool',
            name='icon_image',
            field=models.FileField(blank=True, help_text='SVG icon file', null=True, upload_to='services/project_management/tool_icons/'),
        ),
        migrations.AlterField(
            model_name='pmtoollogo',
            name='logo',
            field=models.FileField(help_text='SVG logo file', upload_to='services/project_management/tool_logos/'),
        ),
        migrations.AlterField(
            model_name='seoauditbenefit',
            name='icon_image',
            field=models.FileField(blank=True, help_text='SVG icon file', null=True, upload_to='services/seo_audit/benefit_icons/'),
        ),
        migrations.AlterField(
            model_name='seoauditservice',
            name='icon_image',
            field=models.FileField(blank=True, help_text='SVG icon file', null=True, upload_to='services/seo_audit/service_icons/'),
        ),
        migrations.AlterField(
            model_name='seoaudittool',
            name='icon_image',
            field=models.FileField(blank=True, help_text='SVG icon file', null=True, upload_to='services/seo_audit/tool_icons/'),
        ),
        migrations.AlterField(
            model_name='seoaudittoollogo',
            name='logo',
            field=models.FileField(help_text='SVG logo file', upload_to='services/seo_audit/tool_logos/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.FileField(blank=True, help_text='SVG service icon', null=True, upload_to='services/'),
        ),
        migrations.AlterField(
            model_name='servicedetail',
            name='image',
            field=models.FileField(blank=True, help_text='SVG service icon', null=True, upload_to='services/'),
        ),
        migrations.AlterField(
            model_name='webdevseobenefit',
            name='icon_image',
            field=models.FileField(blank=True, help_text='SVG icon file', null=True, upload_to='services/web_dev/seo_icons/'),
        ),
        migrations.AlterField(
            model_name='webdevservice',
            name='icon_image',
            field=models.FileField(blank=True, help_text='SVG icon file', null=True, upload_to='services/web_dev/service_icons/'),
        ),
        migrations.AlterField(
            model_name='webdevstackfeature',
            name='icon_image',
            field=models.FileField(blank=True, help_text='SVG icon file', null=True, upload_to='services/web_dev/stack_icons/'),
        ),
        migrations.AlterField(
            model_name='webdevtechnology',
            name='logo',
            field=models.FileField(help_text='SVG logo file', upload_to='services/web_dev/tech_logos/'),
        ),
        migrations.AlterField(
            model_name='whychooseimage',
            name='image',
            field=models.FileField(help_text='SVG image for Why Choose section', upload_to='services/why_choose/'),
        ),
    ]
