# Generated by Django 6.0.2 on 2026-02-15 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0029_alter_airoimetric_icon_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CPBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(help_text='Material icon name', max_length=50)),
                ('icon_image', models.FileField(blank=True, null=True, upload_to='services/content_production/benefit_icons/')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('metric_value', models.CharField(help_text='e.g., 385%, 3.2x', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'CP Benefit',
                'verbose_name_plural': 'CP Benefits',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CPMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=50)),
                ('percentage', models.IntegerField(help_text='Bar width percentage (0-100)')),
                ('color_class', models.CharField(default='green-400', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'CP Metric',
                'verbose_name_plural': 'CP Metrics',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CPProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'CP Process Step',
                'verbose_name_plural': 'CP Process Steps',
                'ordering': ['step_number'],
            },
        ),
        migrations.CreateModel(
            name='CPService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(help_text='Material icon name or SVG path', max_length=50)),
                ('icon_image', models.FileField(blank=True, null=True, upload_to='services/content_production/service_icons/')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('features', models.JSONField(default=list, help_text='List of features')),
                ('color_scheme', models.CharField(choices=[('purple', 'Purple'), ('blue', 'Blue'), ('green', 'Green'), ('orange', 'Orange')], default='blue', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'CP Service',
                'verbose_name_plural': 'CP Services',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CPTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('client_position', models.CharField(max_length=100)),
                ('client_company', models.CharField(max_length=200)),
                ('client_photo', models.URLField(blank=True)),
                ('testimonial_text', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'CP Testimonial',
                'verbose_name_plural': 'CP Testimonials',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CPTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(help_text='Material icon name', max_length=50)),
                ('icon_image', models.FileField(blank=True, null=True, upload_to='services/content_production/tool_icons/')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(help_text='e.g., Design Suite, Video Editing', max_length=100)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'CP Tool',
                'verbose_name_plural': 'CP Tools',
                'ordering': ['order'],
            },
        ),
    ]
