# Generated by Django 6.0.2 on 2026-02-15 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0030_cpbenefit_cpmetric_cpprocessstep_cpservice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CPTechnology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(help_text='Material icon name', max_length=50)),
                ('icon_image', models.FileField(blank=True, null=True, upload_to='services/content_production/tech_icons/')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'CP Technology',
                'verbose_name_plural': 'CP Technologies',
                'ordering': ['order'],
            },
        ),
    ]
