# Generated by Django 6.0.2 on 2026-02-15 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0031_cptechnology'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestimonialsPageCTA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_icon', models.CharField(default='phone', max_length=50)),
                ('badge_text', models.CharField(default='Need Help?', max_length=50)),
                ('headline', models.CharField(default='Ready to Get Started?', max_length=200)),
                ('description', models.TextField(default='Join satisfied clients who trust Techlynx Pro for their digital needs.')),
                ('cta_primary_text', models.CharField(default='Get Your Free Quote', max_length=50)),
                ('cta_primary_url', models.CharField(default='/contact', max_length=200)),
                ('cta_primary_icon', models.CharField(default='arrow_forward', max_length=50)),
                ('cta_secondary_text', models.CharField(default='Call Us Now', max_length=50)),
                ('cta_secondary_url', models.CharField(default='tel:+1234567890', max_length=200)),
                ('cta_secondary_icon', models.CharField(default='phone', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Testimonials CTA',
                'verbose_name_plural': 'Testimonials CTA',
            },
        ),
        migrations.CreateModel(
            name='TestimonialsPageHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_icon', models.CharField(default='rate_review', max_length=50)),
                ('badge_text', models.CharField(default='What Clients Say', max_length=100)),
                ('headline', models.TextField(default='Real Clients. Real Results.')),
                ('subheadline', models.CharField(default='(No Made-Up Quotes.)', max_length=200)),
                ('description', models.TextField(default="We've been helping businesses grow online since 2015. Here's what clients say about working with Techlynx Pro—straight from the people who've actually worked with us.")),
                ('cta_text', models.CharField(default='Get Quote', max_length=50)),
                ('cta_url', models.CharField(default='/contact', max_length=200)),
                ('cta_icon', models.CharField(default='arrow_forward', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Testimonials Hero',
                'verbose_name_plural': 'Testimonials Hero',
            },
        ),
        migrations.CreateModel(
            name='TestimonialsPageSEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(default='Client Testimonials | Real Results from Real Businesses', max_length=60)),
                ('meta_description', models.TextField(default="Read what our clients say about Techlynx Pro. Real testimonials from businesses we've helped grow with AI solutions, web development, and digital marketing.", max_length=160)),
                ('meta_keywords', models.TextField(default='client testimonials, customer reviews, client success stories, business reviews, IT services reviews')),
                ('og_title', models.CharField(default='Real Clients. Real Results. | Techlynx Pro', max_length=60)),
                ('og_description', models.TextField(default="Don't just take our word for it. See what businesses say about working with Techlynx Pro.", max_length=160)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Testimonials SEO',
                'verbose_name_plural': 'Testimonials SEO',
            },
        ),
        migrations.CreateModel(
            name='TestimonialsPageWhyChoose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_icon', models.CharField(default='verified', max_length=50)),
                ('badge_text', models.CharField(default='Why Choose Techlynx Pro', max_length=100)),
                ('headline', models.CharField(default='Three Reasons Clients Stick With Us', max_length=200)),
                ('description', models.TextField(default="We deliver experienced digital development services tailored to your business goals. With satisfied clients, we've proven our commitment to excellence.")),
                ('image_url', models.CharField(default='https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&q=80&w=800', help_text='URL for team collaboration image', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Why Choose Section',
                'verbose_name_plural': 'Why Choose Section',
            },
        ),
        migrations.CreateModel(
            name='TestimonialsPageWhyChooseReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('is_default_open', models.BooleanField(default=False, help_text='Open by default')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Why Choose Reason',
                'verbose_name_plural': 'Why Choose Reasons',
                'ordering': ['order'],
            },
        ),
    ]
