# Generated by Django 6.0.2 on 2026-02-15 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0032_testimonialspagecta_testimonialspagehero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='image_alt_text',
            field=models.CharField(blank=True, help_text='SEO-friendly alt text for the image', max_length=200),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Show on case studies page'),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='key_result_label',
            field=models.CharField(default='Key Result', help_text='E.g., Key Result, User Engagement, Ad Spend', max_length=100),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='key_result_value',
            field=models.CharField(default='+100%', help_text='E.g., 45% Ops Reduction, +150% Growth, 3.5x ROI', max_length=100),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='category',
            field=models.CharField(help_text='E.g., E-commerce, SaaS, Healthcare, Logistics', max_length=100),
        ),
    ]
