# Generated by Django 6.0.2 on 2026-02-15 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0033_casestudy_image_alt_text_casestudy_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='challenge',
            field=models.TextField(blank=True, help_text='Problem/challenge the client faced'),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='client_name',
            field=models.CharField(blank=True, help_text='Client company name', max_length=200),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='industry',
            field=models.CharField(blank=True, help_text='Industry sector', max_length=100),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='project_duration',
            field=models.CharField(blank=True, help_text='E.g., 6 months, 1 year', max_length=100),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='results',
            field=models.TextField(blank=True, help_text='Detailed results and outcomes'),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly version (auto-generated from title)', max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='solution',
            field=models.TextField(blank=True, help_text='How we solved the problem'),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='technologies_used',
            field=models.TextField(blank=True, help_text='Technologies/tools used (comma separated)'),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='testimonial',
            field=models.TextField(blank=True, help_text='Client testimonial quote'),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='testimonial_author',
            field=models.CharField(blank=True, help_text='Testimonial author name and title', max_length=200),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='description',
            field=models.TextField(help_text='Short description for card view'),
        ),
    ]
