# Generated by Django 6.0.2 on 2026-02-15 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0034_casestudy_challenge_casestudy_client_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casestudy',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='casestudy',
            name='project_duration',
        ),
        migrations.RemoveField(
            model_name='casestudy',
            name='technologies_used',
        ),
        migrations.RemoveField(
            model_name='casestudy',
            name='testimonial',
        ),
        migrations.RemoveField(
            model_name='casestudy',
            name='testimonial_author',
        ),
        migrations.RemoveField(
            model_name='casestudy',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='casestudy',
            name='detailed_description',
            field=models.TextField(blank=True, help_text='Full detailed description for detail page'),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='challenge',
            field=models.TextField(blank=True, help_text='The challenge/problem'),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='client_name',
            field=models.CharField(blank=True, help_text='Client company name (optional)', max_length=200),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='description',
            field=models.TextField(help_text='Short description for card'),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='results',
            field=models.TextField(blank=True, help_text='Results achieved'),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='slug',
            field=models.SlugField(help_text='URL-friendly version (auto-generated)', max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='solution',
            field=models.TextField(blank=True, help_text='Our solution'),
        ),
    ]
