# Generated by Django 6.0.2 on 2026-02-15 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0035_remove_casestudy_industry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudiesPageCTA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(default='Ready for Similar Results?', help_text='Main CTA headline', max_length=200)),
                ('description', models.TextField(default="Let's discuss how we can help transform your business with proven strategies and solutions.", help_text='CTA description text')),
                ('primary_button_text', models.CharField(default='Start Your Project', help_text='Primary button text', max_length=50)),
                ('primary_button_url', models.CharField(default='/contact/', help_text='Primary button URL', max_length=200)),
                ('secondary_button_text', models.CharField(default='View More Case Studies', help_text='Secondary button text', max_length=50)),
                ('secondary_button_url', models.CharField(default='/case-studies/', help_text='Secondary button URL', max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='Show this CTA on case study detail pages')),
            ],
            options={
                'verbose_name': 'Case Study Page CTA',
                'verbose_name_plural': 'Case Study Page CTA',
            },
        ),
    ]
