# Generated by Django 6.0.2 on 2026-02-15 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0036_casestudiespagecta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonialspagewhychoose',
            name='image_url',
        ),
        migrations.AddField(
            model_name='testimonialspagewhychoose',
            name='illustration_image',
            field=models.ImageField(blank=True, help_text='Illustration image for the section', null=True, upload_to='testimonials/illustrated/'),
        ),
    ]
