# Generated by Django 6.0.2 on 2026-02-15 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0037_remove_testimonialspagewhychoose_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonialspagewhychoose',
            name='grid_image_1',
            field=models.ImageField(blank=True, help_text='Top-left grid image', null=True, upload_to='services/why_choose/'),
        ),
        migrations.AddField(
            model_name='testimonialspagewhychoose',
            name='grid_image_2',
            field=models.ImageField(blank=True, help_text='Top-right grid image', null=True, upload_to='services/why_choose/'),
        ),
        migrations.AddField(
            model_name='testimonialspagewhychoose',
            name='grid_image_3',
            field=models.ImageField(blank=True, help_text='Bottom-left grid image', null=True, upload_to='services/why_choose/'),
        ),
        migrations.AddField(
            model_name='testimonialspagewhychoose',
            name='grid_image_4',
            field=models.ImageField(blank=True, help_text='Bottom-right grid image', null=True, upload_to='services/why_choose/'),
        ),
    ]
