# Generated by Django 6.0.2 on 2026-02-15 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0038_add_why_choose_grid_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='benefit',
            name='icon_image',
            field=models.FileField(blank=True, help_text='SVG icon (preferred over material icon)', null=True, upload_to='benefits/icons/'),
        ),
        migrations.AddField(
            model_name='companystat',
            name='icon_image',
            field=models.FileField(blank=True, help_text='SVG icon (preferred over material icon)', null=True, upload_to='stats/icons/'),
        ),
        migrations.AddField(
            model_name='guarantee',
            name='icon_image',
            field=models.FileField(blank=True, help_text='SVG icon (preferred over material icon)', null=True, upload_to='guarantees/icons/'),
        ),
        migrations.AddField(
            model_name='herobenefit',
            name='icon_image',
            field=models.FileField(blank=True, help_text='SVG icon (preferred over material icon)', null=True, upload_to='hero/benefit_icons/'),
        ),
    ]
