# Generated by Django 6.0.2 on 2026-02-16 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0039_benefit_icon_image_companystat_icon_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestimonialsPageMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='Metric value (e.g., 340%, 2,200%, 98%, 500+)', max_length=50)),
                ('title', models.CharField(help_text='Metric title', max_length=100)),
                ('description', models.CharField(help_text='Metric description', max_length=200)),
                ('color', models.CharField(choices=[('blue-500', 'Blue'), ('green-500', 'Green'), ('purple-500', 'Purple'), ('orange-500', 'Orange'), ('red-500', 'Red'), ('yellow-500', 'Yellow'), ('pink-500', 'Pink'), ('indigo-500', 'Indigo')], default='blue-500', help_text='Background color for the metric box', max_length=20)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower first)')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Testimonials Page Metric',
                'verbose_name_plural': 'Testimonials Page Metrics',
                'ordering': ['order'],
            },
        ),
    ]
