# Generated by Django 6.0.2 on 2026-02-16 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0040_testimonialspagemetric'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cptestimonial',
            name='client_photo',
            field=models.ImageField(blank=True, null=True, upload_to='testimonials/content_production/'),
        ),
    ]
