# Generated by Django 6.0.2 on 2026-02-16 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0041_alter_cptestimonial_client_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='webdevhero',
            name='badge_icon',
            field=models.CharField(default='code', help_text='Material icon name', max_length=100),
        ),
        migrations.AddField(
            model_name='webdevhero',
            name='lighthouse_score',
            field=models.CharField(blank=True, default='95+', max_length=50),
        ),
        migrations.AddField(
            model_name='webdevhero',
            name='metric_main',
            field=models.CharField(blank=True, default='95+', max_length=100),
        ),
        migrations.AddField(
            model_name='webdevhero',
            name='metric_title',
            field=models.CharField(blank=True, default='Performance Score', max_length=100),
        ),
        migrations.AddField(
            model_name='webdevhero',
            name='process_section_description',
            field=models.TextField(blank=True, default='Transparency at every stage. We follow a rigorous methodology to ensure your project is delivered on time and above expectations.'),
        ),
        migrations.AddField(
            model_name='webdevhero',
            name='process_section_title',
            field=models.CharField(blank=True, default='Our Proven Process', max_length=200),
        ),
        migrations.AddField(
            model_name='webdevhero',
            name='seo_score',
            field=models.CharField(blank=True, default='100%', max_length=50),
        ),
        migrations.AddField(
            model_name='webdevhero',
            name='seo_section_description',
            field=models.TextField(blank=True, default="While other agencies treat SEO as an afterthought, we bake it into the very foundation of your site. Every line of code is written to satisfy Google's most stringent requirements."),
        ),
        migrations.AddField(
            model_name='webdevhero',
            name='seo_section_title',
            field=models.CharField(blank=True, default='Built for Search Engine Dominance', max_length=200),
        ),
        migrations.AddField(
            model_name='webdevhero',
            name='services_section_description',
            field=models.TextField(blank=True, default="We don't just build websites; we build scalable digital infrastructure optimized for search engines and user conversion."),
        ),
        migrations.AddField(
            model_name='webdevhero',
            name='services_section_title',
            field=models.CharField(blank=True, default='Comprehensive Development Solutions', max_length=200),
        ),
        migrations.AddField(
            model_name='webdevhero',
            name='tech_stack_section_description',
            field=models.TextField(blank=True, default='We select the best tools for the job, ensuring your site is fast, maintainable, and highly visible to search engines.'),
        ),
        migrations.AddField(
            model_name='webdevhero',
            name='tech_stack_section_title',
            field=models.CharField(blank=True, default='Our Core Tech Stack', max_length=200),
        ),
    ]
