# Generated by Django 6.0.2 on 2026-02-16 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0042_add_webdev_hero_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='aisolutionshero',
            name='automation_rate_label',
            field=models.CharField(blank=True, default='Automation Rate', max_length=100),
        ),
        migrations.AddField(
            model_name='aisolutionshero',
            name='performance_metrics_title',
            field=models.CharField(blank=True, default='AI Performance Metrics', max_length=200),
        ),
        migrations.AddField(
            model_name='aisolutionshero',
            name='process_section_description',
            field=models.TextField(blank=True, default='From ideation to deployment, we follow a proven framework that ensures your AI solution delivers measurable ROI.'),
        ),
        migrations.AddField(
            model_name='aisolutionshero',
            name='process_section_title',
            field=models.CharField(blank=True, default='Our AI Implementation Methodology', max_length=200),
        ),
        migrations.AddField(
            model_name='aisolutionshero',
            name='roi_section_description',
            field=models.TextField(blank=True, default="Our AI solutions don't just automate—they transform. See how businesses like yours are achieving unprecedented efficiency and growth with intelligent automation."),
        ),
        migrations.AddField(
            model_name='aisolutionshero',
            name='roi_section_title',
            field=models.CharField(blank=True, default='Measurable AI-Driven Results', max_length=200),
        ),
        migrations.AddField(
            model_name='aisolutionshero',
            name='services_section_description',
            field=models.TextField(blank=True, default="We don't just implement AI; we engineer intelligent systems that adapt, learn, and scale with your business needs."),
        ),
        migrations.AddField(
            model_name='aisolutionshero',
            name='services_section_title',
            field=models.CharField(blank=True, default='Comprehensive AI Solutions', max_length=200),
        ),
        migrations.AddField(
            model_name='aisolutionshero',
            name='tech_stack_section_description',
            field=models.TextField(blank=True, default='We leverage industry-leading AI platforms and frameworks to build robust, scalable solutions tailored to your unique challenges.'),
        ),
        migrations.AddField(
            model_name='aisolutionshero',
            name='tech_stack_section_title',
            field=models.CharField(blank=True, default='Cutting-Edge AI Frameworks', max_length=200),
        ),
        migrations.AddField(
            model_name='aisolutionshero',
            name='time_saved_label',
            field=models.CharField(blank=True, default='Time Saved', max_length=100),
        ),
    ]
