# Generated by Django 6.0.2 on 2026-02-16 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0043_add_ai_solutions_hero_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalmarketingcta',
            name='footer_text',
            field=models.CharField(blank=True, default='Free marketing audit included with every consultation.', max_length=200),
        ),
        migrations.AddField(
            model_name='digitalmarketinghero',
            name='avg_cpc_label',
            field=models.CharField(blank=True, default='Avg. CPC Saved', max_length=100),
        ),
        migrations.AddField(
            model_name='digitalmarketinghero',
            name='conversion_rate_label',
            field=models.CharField(blank=True, default='Conversion Rate', max_length=100),
        ),
        migrations.AddField(
            model_name='digitalmarketinghero',
            name='metric_main',
            field=models.CharField(blank=True, default='+248% Revenue', max_length=100),
        ),
        migrations.AddField(
            model_name='digitalmarketinghero',
            name='metric_title',
            field=models.CharField(blank=True, default='Growth Forecast', max_length=100),
        ),
        migrations.AddField(
            model_name='digitalmarketinghero',
            name='metrics_section_description',
            field=models.TextField(blank=True, default='Track your success with real-time metrics and comprehensive reporting dashboards.'),
        ),
        migrations.AddField(
            model_name='digitalmarketinghero',
            name='metrics_section_title',
            field=models.CharField(blank=True, default='Transparent Growth Monitoring', max_length=200),
        ),
        migrations.AddField(
            model_name='digitalmarketinghero',
            name='services_section_description',
            field=models.TextField(blank=True, default='We don\'t just "run ads." We engineer full-funnel growth engines using the most effective digital channels.'),
        ),
        migrations.AddField(
            model_name='digitalmarketinghero',
            name='services_section_title',
            field=models.CharField(blank=True, default='Our Specialized Growth Services', max_length=200),
        ),
        migrations.AddField(
            model_name='digitalmarketinghero',
            name='strategy_section_description',
            field=models.TextField(blank=True, default='A proven, data-driven methodology that consistently delivers exceptional results for our clients.'),
        ),
        migrations.AddField(
            model_name='digitalmarketinghero',
            name='strategy_section_title',
            field=models.CharField(blank=True, default='The Strategy-First Approach', max_length=200),
        ),
    ]
