# Generated by Django 6.0.2 on 2026-02-16 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0044_add_digital_marketing_hero_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='appdevhero',
            name='downloads_label',
            field=models.CharField(blank=True, default='Downloads', max_length=100),
        ),
        migrations.AddField(
            model_name='appdevhero',
            name='downloads_value',
            field=models.CharField(blank=True, default='5M+', max_length=50),
        ),
        migrations.AddField(
            model_name='appdevhero',
            name='features_section_description',
            field=models.TextField(blank=True, default='Every app we build comes with essential features for security, performance, and user engagement that drive business results.'),
        ),
        migrations.AddField(
            model_name='appdevhero',
            name='features_section_title',
            field=models.CharField(blank=True, default='Enterprise-Grade Features Built In', max_length=200),
        ),
        migrations.AddField(
            model_name='appdevhero',
            name='metric_main',
            field=models.CharField(blank=True, default='+320% Growth', max_length=100),
        ),
        migrations.AddField(
            model_name='appdevhero',
            name='metric_title',
            field=models.CharField(blank=True, default='User Engagement', max_length=100),
        ),
        migrations.AddField(
            model_name='appdevhero',
            name='performance_metrics_title',
            field=models.CharField(blank=True, default='App Performance Metrics', max_length=200),
        ),
        migrations.AddField(
            model_name='appdevhero',
            name='process_section_description',
            field=models.TextField(blank=True, default='From wireframes to App Store launch, we follow a structured approach that ensures quality at every stage.'),
        ),
        migrations.AddField(
            model_name='appdevhero',
            name='process_section_title',
            field=models.CharField(blank=True, default='App Development Process', max_length=200),
        ),
        migrations.AddField(
            model_name='appdevhero',
            name='retention_label',
            field=models.CharField(blank=True, default='Retention', max_length=100),
        ),
        migrations.AddField(
            model_name='appdevhero',
            name='retention_value',
            field=models.CharField(blank=True, default='87%', max_length=50),
        ),
        migrations.AddField(
            model_name='appdevhero',
            name='services_section_description',
            field=models.TextField(blank=True, default='From concept to launch and beyond, we build mobile applications that combine stunning design with robust functionality.'),
        ),
        migrations.AddField(
            model_name='appdevhero',
            name='services_section_title',
            field=models.CharField(blank=True, default='Complete App Development Services', max_length=200),
        ),
        migrations.AddField(
            model_name='appdevhero',
            name='tech_stack_section_description',
            field=models.TextField(blank=True, default='We use cutting-edge frameworks and tools to build fast, secure, and scalable mobile applications.'),
        ),
        migrations.AddField(
            model_name='appdevhero',
            name='tech_stack_section_title',
            field=models.CharField(blank=True, default='Modern Mobile Tech Stack', max_length=200),
        ),
    ]
