# Generated by Django 6.0.2 on 2026-02-16 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0045_add_app_dev_hero_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='seoaudithero',
            name='domain_authority_label',
            field=models.CharField(blank=True, default='Domain Authority', max_length=100),
        ),
        migrations.AddField(
            model_name='seoaudithero',
            name='health_metrics_title',
            field=models.CharField(blank=True, default='SEO Health Score', max_length=200),
        ),
        migrations.AddField(
            model_name='seoaudithero',
            name='keywords_ranked_label',
            field=models.CharField(blank=True, default='Keywords Ranked', max_length=100),
        ),
        migrations.AddField(
            model_name='seoaudithero',
            name='metric_main',
            field=models.CharField(blank=True, default='+475% Traffic Increase', max_length=100),
        ),
        migrations.AddField(
            model_name='seoaudithero',
            name='metric_title',
            field=models.CharField(blank=True, default='Organic Growth', max_length=100),
        ),
        migrations.AddField(
            model_name='seoaudithero',
            name='process_section_description',
            field=models.TextField(blank=True, default='Thorough analysis followed by prioritized action plans that drive measurable improvements.'),
        ),
        migrations.AddField(
            model_name='seoaudithero',
            name='process_section_title',
            field=models.CharField(blank=True, default='Our SEO Audit Process', max_length=200),
        ),
        migrations.AddField(
            model_name='seoaudithero',
            name='results_section_description',
            field=models.TextField(blank=True, default='Our comprehensive SEO audits reveal hidden opportunities and provide actionable strategies to boost your search rankings.'),
        ),
        migrations.AddField(
            model_name='seoaudithero',
            name='results_section_title',
            field=models.CharField(blank=True, default='Measurable SEO Improvements', max_length=200),
        ),
        migrations.AddField(
            model_name='seoaudithero',
            name='services_section_description',
            field=models.TextField(blank=True, default='Deep-dive analysis across all critical SEO factors that impact your search visibility and organic performance.'),
        ),
        migrations.AddField(
            model_name='seoaudithero',
            name='services_section_title',
            field=models.CharField(blank=True, default='Complete SEO Audit Services', max_length=200),
        ),
        migrations.AddField(
            model_name='seoaudithero',
            name='tools_section_description',
            field=models.TextField(blank=True, default='We leverage industry-leading SEO tools to deliver comprehensive audits and actionable recommendations.'),
        ),
        migrations.AddField(
            model_name='seoaudithero',
            name='tools_section_title',
            field=models.CharField(blank=True, default='Enterprise SEO Tools & Platforms', max_length=200),
        ),
    ]
