# Generated by Django 6.0.2 on 2026-02-16 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0046_add_seo_audit_hero_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='seoaudithero',
            name='domain_authority_value',
            field=models.CharField(blank=True, default='DA 68', max_length=50),
        ),
        migrations.AddField(
            model_name='seoaudithero',
            name='keywords_ranked_value',
            field=models.CharField(blank=True, default='1,247', max_length=50),
        ),
    ]
