# Generated by Django 6.0.2 on 2026-02-16 18:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0047_add_seo_audit_hero_metric_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Privacy Policy', max_length=200)),
                ('last_updated', models.DateField(default=django.utils.timezone.now)),
                ('introduction', models.TextField(help_text='Introduction paragraph')),
                ('contact_email', models.EmailField(default='privacy@techlynxpro.com', max_length=254)),
                ('contact_url', models.CharField(default='/contact/', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Privacy Policy',
                'verbose_name_plural': 'Privacy Policy',
            },
        ),
        migrations.RemoveField(
            model_name='seoaudithero',
            name='domain_authority_label',
        ),
        migrations.RemoveField(
            model_name='seoaudithero',
            name='domain_authority_value',
        ),
        migrations.RemoveField(
            model_name='seoaudithero',
            name='health_metrics_title',
        ),
        migrations.RemoveField(
            model_name='seoaudithero',
            name='keywords_ranked_label',
        ),
        migrations.RemoveField(
            model_name='seoaudithero',
            name='keywords_ranked_value',
        ),
        migrations.RemoveField(
            model_name='seoaudithero',
            name='metric_main',
        ),
        migrations.RemoveField(
            model_name='seoaudithero',
            name='metric_title',
        ),
        migrations.RemoveField(
            model_name='seoaudithero',
            name='process_section_description',
        ),
        migrations.RemoveField(
            model_name='seoaudithero',
            name='process_section_title',
        ),
        migrations.RemoveField(
            model_name='seoaudithero',
            name='results_section_description',
        ),
        migrations.RemoveField(
            model_name='seoaudithero',
            name='results_section_title',
        ),
        migrations.RemoveField(
            model_name='seoaudithero',
            name='services_section_description',
        ),
        migrations.RemoveField(
            model_name='seoaudithero',
            name='services_section_title',
        ),
        migrations.RemoveField(
            model_name='seoaudithero',
            name='tools_section_description',
        ),
        migrations.RemoveField(
            model_name='seoaudithero',
            name='tools_section_title',
        ),
        migrations.CreateModel(
            name='PrivacyPolicySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_number', models.IntegerField(help_text='Section number (e.g., 1, 2, 3)')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(help_text='Section content (supports HTML)')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='website.privacypolicy')),
            ],
            options={
                'verbose_name': 'Privacy Policy Section',
                'verbose_name_plural': 'Privacy Policy Sections',
                'ordering': ['order', 'section_number'],
            },
        ),
        migrations.CreateModel(
            name='PrivacyPolicySubsection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(help_text='Subsection content (supports HTML)')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsections', to='website.privacypolicysection')),
            ],
            options={
                'verbose_name': 'Privacy Policy Subsection',
                'verbose_name_plural': 'Privacy Policy Subsections',
                'ordering': ['order'],
            },
        ),
    ]
