# Generated by Django 6.0.2 on 2026-02-16 18:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0048_privacypolicy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermsOfService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Terms of Service', max_length=200)),
                ('last_updated', models.DateField(default=django.utils.timezone.now)),
                ('introduction', models.TextField(help_text='Introduction paragraph')),
                ('contact_email', models.EmailField(default='legal@techlynxpro.com', max_length=254)),
                ('contact_url', models.CharField(default='/contact/', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Terms of Service',
                'verbose_name_plural': 'Terms of Service',
            },
        ),
        migrations.CreateModel(
            name='TermsOfServiceSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_number', models.IntegerField(help_text='Section number (e.g., 1, 2, 3)')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(help_text='Section content (supports HTML)')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('terms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='website.termsofservice')),
            ],
            options={
                'verbose_name': 'Terms of Service Section',
                'verbose_name_plural': 'Terms of Service Sections',
                'ordering': ['order', 'section_number'],
            },
        ),
        migrations.CreateModel(
            name='TermsOfServiceSubsection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(help_text='Subsection content (supports HTML)')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsections', to='website.termsofservicesection')),
            ],
            options={
                'verbose_name': 'Terms of Service Subsection',
                'verbose_name_plural': 'Terms of Service Subsections',
                'ordering': ['order'],
            },
        ),
    ]
