# Generated by Django 6.0.2 on 2026-02-16 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0050_alter_privacypolicy_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='privacypolicy',
            options={'verbose_name': 'Privacy Policy', 'verbose_name_plural': 'Privacy Policy'},
        ),
        migrations.AlterModelOptions(
            name='termsofservice',
            options={'verbose_name': 'Terms of Service', 'verbose_name_plural': 'Terms of Service'},
        ),
    ]
