# Generated by Django 6.0.2 on 2026-02-16 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0051_alter_privacypolicy_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='termsofservice',
            name='content_field_1',
            field=models.TextField(blank=True, help_text='First content section (supports HTML)'),
        ),
        migrations.AddField(
            model_name='termsofservice',
            name='content_field_2',
            field=models.TextField(blank=True, help_text='Second content section (supports HTML)'),
        ),
        migrations.AddField(
            model_name='termsofservice',
            name='content_field_3',
            field=models.TextField(blank=True, help_text='Third content section (supports HTML)'),
        ),
    ]
