# Generated by Django 6.0.2 on 2026-02-16 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0052_termsofservice_content_field_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='termsofservice',
            name='content_field_1',
        ),
        migrations.RemoveField(
            model_name='termsofservice',
            name='content_field_2',
        ),
        migrations.RemoveField(
            model_name='termsofservice',
            name='content_field_3',
        ),
        migrations.AddField(
            model_name='termsofservice',
            name='content',
            field=models.TextField(blank=True, help_text='Main content section (supports HTML)'),
        ),
    ]
