# Generated by Django 6.0.2 on 2026-02-16 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0053_remove_termsofservice_content_field_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='privacypolicy',
            name='content',
            field=models.TextField(blank=True, help_text='Main content section (supports HTML)'),
        ),
    ]
