# Generated by Django 6.0.2 on 2026-02-16 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0054_privacypolicy_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinquiry',
            name='company',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='contactinquiry',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text="User's IP address", null=True),
        ),
        migrations.AddField(
            model_name='contactinquiry',
            name='is_read',
            field=models.BooleanField(default=False, help_text='Mark as read in admin'),
        ),
        migrations.AddField(
            model_name='contactinquiry',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal notes about this inquiry'),
        ),
        migrations.AddField(
            model_name='contactinquiry',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='contactinquiry',
            name='referrer_url',
            field=models.CharField(blank=True, help_text='Referrer URL (where user came from)', max_length=500),
        ),
        migrations.AddField(
            model_name='contactinquiry',
            name='source_url',
            field=models.CharField(blank=True, help_text='URL where form was submitted from', max_length=500),
        ),
        migrations.AddField(
            model_name='contactinquiry',
            name='user_agent',
            field=models.TextField(blank=True, help_text="User's browser and device information"),
        ),
        migrations.AddField(
            model_name='contactinquiry',
            name='utm_campaign',
            field=models.CharField(blank=True, help_text='UTM campaign parameter', max_length=100),
        ),
        migrations.AddField(
            model_name='contactinquiry',
            name='utm_medium',
            field=models.CharField(blank=True, help_text='UTM medium parameter', max_length=100),
        ),
        migrations.AddField(
            model_name='contactinquiry',
            name='utm_source',
            field=models.CharField(blank=True, help_text='UTM source parameter', max_length=100),
        ),
    ]
