# Generated by Django 6.0.2 on 2026-02-16 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0055_contactinquiry_company_contactinquiry_ip_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinquiry',
            name='country',
            field=models.CharField(blank=True, help_text='Country from which form was submitted', max_length=100),
        ),
    ]
