# Generated by Django 6.0.2 on 2026-02-16 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0056_contactinquiry_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whychooseimage',
            name='image',
            field=models.ImageField(help_text='Image for Why Choose section (JPG, PNG, SVG supported)', upload_to='services/why_choose/'),
        ),
    ]
