# Generated by Django 6.0.2 on 2026-02-16 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0057_alter_whychooseimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='whychooseimage',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Show this image on the services page'),
        ),
    ]
