# Generated by Django 6.0.2 on 2026-02-16 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0058_whychooseimage_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicespagehero',
            name='hero_image_alt_text',
            field=models.CharField(blank=True, help_text='Alt text for hero image (SEO)', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='servicespagehero',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Hero section image', null=True, upload_to='services/hero/'),
        ),
    ]
