# Generated by Django 6.0.2 on 2026-02-16 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0059_servicespagehero_hero_image_alt_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPageAdvantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon', models.CharField(help_text='Material icon name', max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'About Page Advantage',
                'verbose_name_plural': 'About Page Advantages',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AboutPageAdvantageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_text', models.CharField(default='Why Work With Us', max_length=100)),
                ('title', models.CharField(default='The Techlynx Advantage', max_length=200)),
                ('description', models.TextField(default='We combine domestic management with global technical excellence to provide a seamless experience for enterprise clients.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'About Page Advantage Section',
                'verbose_name_plural': 'About Page Advantage Section',
            },
        ),
        migrations.CreateModel(
            name='AboutPageCTA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(default='Ready to elevate your digital presence?', max_length=200)),
                ('description', models.TextField(default="Join the hundreds of businesses scaling faster with Techlynx Pro's SEO-first methodology and US-based expertise.")),
                ('cta_primary_text', models.CharField(default='Start Your Project', max_length=100)),
                ('cta_primary_url', models.CharField(default='/contact/', max_length=200)),
                ('cta_secondary_text', models.CharField(default='View Our Work', max_length=100)),
                ('cta_secondary_url', models.CharField(default='/case-studies/', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'About Page CTA',
                'verbose_name_plural': 'About Page CTA',
            },
        ),
        migrations.CreateModel(
            name='AboutPageHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(default='Empowering Brands through US-Led Digital Innovation', max_length=200)),
                ('headline_highlight', models.CharField(default='US-Led', help_text='Text to highlight in headline', max_length=50)),
                ('description', models.TextField(default='Techlynx Pro delivers high-performance, SEO-first digital marketing and IT solutions with a focus on brand authority and scalable infrastructure.')),
                ('background_image', models.ImageField(blank=True, help_text='Hero background image', null=True, upload_to='about/hero/')),
                ('background_image_url', models.URLField(blank=True, help_text='Or use external image URL', null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'About Page Hero',
                'verbose_name_plural': 'About Page Hero',
            },
        ),
        migrations.CreateModel(
            name='AboutPageMissionVision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission_title', models.CharField(default='Our Mission', max_length=100)),
                ('mission_text', models.TextField(default='To empower businesses with SEO-first strategies and scalable digital infrastructure that drives measurable growth and sustainable market dominance in an ever-evolving digital landscape.')),
                ('mission_icon', models.CharField(default='target', help_text='Material icon name', max_length=50)),
                ('vision_title', models.CharField(default='Our Vision', max_length=100)),
                ('vision_text', models.TextField(default='To be the global leader in high-performance IT solutions, setting the universal standard for digital excellence, operational integrity, and client-centric innovation.')),
                ('vision_icon', models.CharField(default='visibility', help_text='Material icon name', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'About Page Mission & Vision',
                'verbose_name_plural': 'About Page Mission & Vision',
            },
        ),
        migrations.CreateModel(
            name='AboutPageSEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(default='About Techlynx Pro | US-Based IT Experts with 10+ Years Experience', max_length=60)),
                ('meta_description', models.TextField(default='Meet the team behind 500+ successful IT projects. US-based experts with 10+ years experience in web development, AI solutions, and digital marketing. Our mission: deliver enterprise-grade technology with 98% client retention and 200% average ROI.')),
                ('meta_keywords', models.TextField(default='about us, IT company, US-based developers, expert team, company mission, technology experts, software development company, digital agency, enterprise solutions, certified professionals')),
                ('og_title', models.CharField(default='About Techlynx Pro | Expert US-Based IT Team Since 2015', max_length=60)),
                ('og_description', models.TextField(default='10+ years delivering enterprise IT solutions. 500+ projects, 98% retention, 200% ROI. Meet our certified US-based team.')),
            ],
            options={
                'verbose_name': 'About Page SEO',
                'verbose_name_plural': 'About Page SEO',
            },
        ),
        migrations.CreateModel(
            name='AboutPageTeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='about/team/')),
                ('photo_url', models.URLField(blank=True, help_text='Or use external image URL', null=True)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'About Page Team Member',
                'verbose_name_plural': 'About Page Team Members',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AboutPageTeamSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Meet the Leadership', max_length=200)),
                ('description', models.TextField(default='Decades of combined experience in digital transformation.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'About Page Team Section',
                'verbose_name_plural': 'About Page Team Section',
            },
        ),
        migrations.CreateModel(
            name='AboutPageTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(help_text="Year or 'Present'", max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('position', models.CharField(choices=[('left', 'Left'), ('right', 'Right')], default='left', help_text='Position on timeline', max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'About Page Timeline Milestone',
                'verbose_name_plural': 'About Page Timeline Milestones',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AboutPageTimelineSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Our Growth Story', max_length=200)),
                ('description', models.TextField(default='A journey of innovation and excellence since our inception.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'About Page Timeline Section',
                'verbose_name_plural': 'About Page Timeline Section',
            },
        ),
    ]
