# Generated by Django 6.0.2 on 2026-02-16 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0060_aboutpageadvantage_aboutpageadvantagesection_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutpageadvantage',
            options={'ordering': ['order'], 'verbose_name': 'About Page Advantage', 'verbose_name_plural': '📄 About Page Advantages'},
        ),
        migrations.AlterModelOptions(
            name='aboutpageadvantagesection',
            options={'verbose_name': 'About Page Advantage Section', 'verbose_name_plural': '📄 About Page Advantage Section'},
        ),
        migrations.AlterModelOptions(
            name='aboutpagecta',
            options={'verbose_name': 'About Page CTA', 'verbose_name_plural': '📄 About Page CTA'},
        ),
        migrations.AlterModelOptions(
            name='aboutpagehero',
            options={'verbose_name': 'About Page Hero', 'verbose_name_plural': '📄 About Page Hero'},
        ),
        migrations.AlterModelOptions(
            name='aboutpagemissionvision',
            options={'verbose_name': 'About Page Mission & Vision', 'verbose_name_plural': '📄 About Page Mission & Vision'},
        ),
        migrations.AlterModelOptions(
            name='aboutpageseo',
            options={'verbose_name': 'About Page SEO', 'verbose_name_plural': '📄 About Page SEO'},
        ),
        migrations.AlterModelOptions(
            name='aboutpageteammember',
            options={'ordering': ['order'], 'verbose_name': 'About Page Team Member', 'verbose_name_plural': '📄 About Page Team Members'},
        ),
        migrations.AlterModelOptions(
            name='aboutpageteamsection',
            options={'verbose_name': 'About Page Team Section', 'verbose_name_plural': '📄 About Page Team Section'},
        ),
        migrations.AlterModelOptions(
            name='aboutpagetimeline',
            options={'ordering': ['order'], 'verbose_name': 'About Page Timeline Milestone', 'verbose_name_plural': '📄 About Page Timeline Milestones'},
        ),
        migrations.AlterModelOptions(
            name='aboutpagetimelinesection',
            options={'verbose_name': 'About Page Timeline Section', 'verbose_name_plural': '📄 About Page Timeline Section'},
        ),
    ]
