# Generated by Django 6.0.2 on 2026-02-22

from django.db import migrations


def populate_partners(apps, schema_editor):
    """Add 5 partner logos from media/partners (1.svg–5.svg) to DB."""
    Partner = apps.get_model('website', 'Partner')
    partners_data = [
        {'name': 'Partner 1', 'logo': 'partners/1.svg', 'order': 1},
        {'name': 'Partner 2', 'logo': 'partners/2.svg', 'order': 2},
        {'name': 'Partner 3', 'logo': 'partners/3.svg', 'order': 3},
        {'name': 'Partner 4', 'logo': 'partners/4.svg', 'order': 4},
        {'name': 'Partner 5', 'logo': 'partners/5.svg', 'order': 5},
    ]
    for data in partners_data:
        Partner.objects.get_or_create(
            name=data['name'],
            defaults={'logo': data['logo'], 'order': data['order'], 'website_url': ''},
        )


def reverse_populate_partners(apps, schema_editor):
    """Remove the 5 populated partners."""
    Partner = apps.get_model('website', 'Partner')
    names = ['Partner 1', 'Partner 2', 'Partner 3', 'Partner 4', 'Partner 5']
    Partner.objects.filter(name__in=names).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0061_alter_aboutpageadvantage_options_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_partners, reverse_populate_partners),
    ]
