# Generated by Django 6.0.2 on 2026-02-22 18:02

from django.db import migrations, models


def create_default_trusted_by_headline(apps, schema_editor):
    TrustedBySection = apps.get_model('website', 'TrustedBySection')
    if not TrustedBySection.objects.exists():
        TrustedBySection.objects.create(headline='Trusted by {count}+ Global Enterprises')


def reverse_create(apps, schema_editor):
    TrustedBySection = apps.get_model('website', 'TrustedBySection')
    TrustedBySection.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0062_populate_partners'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrustedBySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(default='Trusted by {count}+ Global Enterprises', help_text='Full text shown above partner logos. Use {count} to show dynamic partner count (e.g. 5+).', max_length=255)),
            ],
            options={
                'verbose_name': 'Trusted By Headline',
                'verbose_name_plural': 'Trusted By Headline',
            },
        ),
        migrations.RunPython(create_default_trusted_by_headline, reverse_create),
    ]
