# Generated by Django 6.0.2 on 2026-02-22 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0063_add_trusted_by_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='trusted_by_headline',
            field=models.CharField(blank=True, default='', help_text="Homepage headline above partner logos. Only the first partner's value is used. Use {count} for dynamic number (e.g. Trusted by {count}+ Global Enterprises).", max_length=255),
        ),
        migrations.AlterField(
            model_name='trustedbysection',
            name='headline',
            field=models.CharField(default='Trusted by {count}+ Global Enterprises', max_length=255),
        ),
    ]
