# Generated by Django 6.0.2 on 2026-02-22

from django.db import migrations


def copy_headline_to_first_partner(apps, schema_editor):
    TrustedBySection = apps.get_model('website', 'TrustedBySection')
    Partner = apps.get_model('website', 'Partner')
    obj = TrustedBySection.objects.first()
    first_partner = Partner.objects.order_by('order').first()
    if obj and obj.headline and first_partner is not None:
        first_partner.trusted_by_headline = obj.headline
        first_partner.save()


def reverse_copy(apps, schema_editor):
    pass  # Cannot restore TrustedBySection data


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0064_partner_trusted_by_headline'),
    ]

    operations = [
        migrations.RunPython(copy_headline_to_first_partner, reverse_copy),
        migrations.DeleteModel(name='TrustedBySection'),
    ]
