# Generated by Django 6.0.2 on 2026-02-22

from django.db import migrations, models


def update_badge_text(apps, schema_editor):
    ServicesPageHero = apps.get_model('website', 'ServicesPageHero')
    ServicesPageHero.objects.filter(badge_text="Trusted US-Based Agency").update(
        badge_text="Trusted Global Digital Partner"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0065_remove_trustedbysection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicespagehero',
            name='badge_text',
            field=models.CharField(default='Trusted Global Digital Partner', help_text='Top badge text', max_length=100),
        ),
        migrations.RunPython(update_badge_text, migrations.RunPython.noop),
    ]
