# Generated by Django 6.0.2 on 2026-02-22 18:34

from django.db import migrations, models


def create_default_section(apps, schema_editor):
    WhyChooseSection = apps.get_model('website', 'WhyChooseSection')
    if not WhyChooseSection.objects.exists():
        WhyChooseSection.objects.create(
            headline="Why Choose Techlynx Pro",
            description="We combine US-based technical excellence with an SEO-first methodology to deliver measurable results that impact your bottom line.",
        )


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0066_services_badge_trusted_global_partner'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhyChooseSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(default='Why Choose Techlynx Pro', help_text='Section headline (e.g. Why Choose Techlynx Pro)', max_length=200)),
                ('description', models.TextField(default='We combine US-based technical excellence with an SEO-first methodology to deliver measurable results that impact your bottom line.', help_text='Section description below the headline')),
            ],
            options={
                'verbose_name': 'Why Choose Section (Headline)',
                'verbose_name_plural': 'Why Choose Section (Headline)',
            },
        ),
        migrations.RunPython(create_default_section, migrations.RunPython.noop),
    ]
