# Generated by Django 6.0.2 on 2026-02-22 18:49

from django.db import migrations, models


def update_since_2020(apps, schema_editor):
    TestimonialsPageHero = apps.get_model('website', 'TestimonialsPageHero')
    for hero in TestimonialsPageHero.objects.all():
        if 'since 2015' in (hero.description or ''):
            hero.description = (hero.description or '').replace('since 2015', 'since 2020')
            hero.save()


def update_ai_testimonial_female_name(apps, schema_editor):
    AITestimonial = apps.get_model('website', 'AITestimonial')
    AITestimonial.objects.filter(client_name='James Robertson').update(client_name='Sarah Robertson')


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0067_why_choose_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonialspagehero',
            name='description',
            field=models.TextField(default="We've been helping businesses grow online since 2020. Here's what clients say about working with Techlynx Pro—straight from the people who've actually worked with us."),
        ),
        migrations.RunPython(update_since_2020, noop),
        migrations.RunPython(update_ai_testimonial_female_name, noop),
    ]
