# Generated by Django 6.0.2 on 2026-02-22

from django.db import migrations


def update_ai_testimonial_name(apps, schema_editor):
    AITestimonial = apps.get_model('website', 'AITestimonial')
    # Sarah Robertson -> Emma Wilson (female name for AI testimonial with female image)
    AITestimonial.objects.filter(client_name='Sarah Robertson').update(client_name='Emma Wilson')


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0068_testimonials_since_2020_and_ai_client_name'),
    ]

    operations = [
        migrations.RunPython(update_ai_testimonial_name, noop),
    ]
