# Generated by Django 6.0.2 on 2026-02-23 19:44

from django.db import migrations, models


def create_contact_page_data(apps, schema_editor):
    ContactPage = apps.get_model('website', 'ContactPage')
    ContactPageFeature = apps.get_model('website', 'ContactPageFeature')
    ContactPageFAQ = apps.get_model('website', 'ContactPageFAQ')
    if not ContactPage.objects.exists():
        ContactPage.objects.create()
    if not ContactPageFeature.objects.exists():
        ContactPageFeature.objects.bulk_create([
            ContactPageFeature(icon='schedule', title='Fast Response', description='Get a response within 24 hours on business days', order=1),
            ContactPageFeature(icon='workspace_premium', title='Expert Team', description='Certified professionals with 15+ years experience', order=2),
            ContactPageFeature(icon='verified_user', title='No Obligation', description='Free consultation and project assessment', order=3),
        ])
    if not ContactPageFAQ.objects.exists():
        ContactPageFAQ.objects.bulk_create([
            ContactPageFAQ(question='How long does it take to get a response?', answer='We typically respond to all inquiries within 24 hours during business days. For urgent requests, please call us directly.', order=1),
            ContactPageFAQ(question='Do you offer free consultations?', answer="Yes! We provide a free initial consultation to discuss your project requirements, goals, and how we can help you achieve them.", order=2),
            ContactPageFAQ(question='What information should I include in my message?', answer='Please include details about your project goals, timeline, budget range, and any specific requirements. The more information you provide, the better we can tailor our response to your needs.', order=3),
            ContactPageFAQ(question='Do you work with international clients?', answer='Absolutely! We work with clients worldwide and have experience managing projects across different time zones and regions.', order=4),
        ])


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0069_ai_testimonial_client_name_emma_wilson'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_text', models.CharField(default="Let's Connect", max_length=100)),
                ('headline', models.CharField(default='Ready to Transform Your Digital Presence?', max_length=300)),
                ('hero_description', models.TextField(default='Get a custom proposal from our expert team. Most inquiries receive a detailed response within 24 hours.')),
                ('form_heading', models.CharField(default='Send Us a Message', max_length=200)),
                ('submit_button_text', models.CharField(default='Send Message', max_length=100)),
                ('get_in_touch_heading', models.CharField(default='Get In Touch', max_length=200)),
                ('get_in_touch_intro', models.TextField(default="Have questions? Our team is here to help. Reach out through any of these channels and we'll get back to you promptly.")),
                ('email_label', models.CharField(default='Email Us', max_length=100)),
                ('email_description', models.CharField(default='Direct inquiries to our team', max_length=200)),
                ('email_address', models.EmailField(default='hello@techlynxpro.com', max_length=254)),
                ('phone_label', models.CharField(default='Call Sales', max_length=100)),
                ('phone_description', models.CharField(default='Mon-Fri, 9am - 6pm EST', max_length=200)),
                ('phone_number', models.CharField(default='+1 (520) 666-4699', max_length=50)),
                ('location_label', models.CharField(default='Office Location', max_length=100)),
                ('location_description', models.CharField(default='Visit our headquarters', max_length=200)),
                ('address_line1', models.CharField(default='123 Business Avenue', max_length=200)),
                ('address_line2', models.CharField(blank=True, default='Suite 500, New York, NY 10001', max_length=200)),
                ('live_chat_label', models.CharField(default='Live Chat', max_length=100)),
                ('live_chat_description', models.CharField(default='Available during business hours', max_length=200)),
                ('live_chat_button_text', models.CharField(default='Start Chat →', max_length=100)),
                ('faq_heading', models.CharField(default='Frequently Asked Questions', max_length=200)),
                ('faq_subtext', models.CharField(default='Quick answers to common questions', max_length=200)),
            ],
            options={
                'verbose_name': 'Contact Page Content',
                'verbose_name_plural': 'Contact Page Content',
            },
        ),
        migrations.CreateModel(
            name='ContactPageFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('answer', models.TextField()),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Contact Page FAQ',
                'verbose_name_plural': 'Contact Page FAQs',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ContactPageFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='schedule', max_length=100)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Contact Page Feature',
                'verbose_name_plural': 'Contact Page Features',
                'ordering': ['order'],
            },
        ),
        migrations.RunPython(create_contact_page_data, migrations.RunPython.noop),
    ]
